### ISSUE TITLE
Align jade & slim document template

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor-reveal.js#104]
* The revealjsdir attribute is only supported in Slim Template - https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/slim/document.html.slim#L5 and not within the Jade Template.
This modification is required in order to use asciidoctor-template & asciidoctor.js. [SOLVED WITH #95]
* Support attr - asset_uri_scheme, revealjs_customtheme, iconfont-name
* Slim reference FontAwesome 4.3 while jade 4.4.
* This list should be be EXTENDED when the slim page will be reviewed completely against jade page

**Comment by mojavelinux** [comment]
> This list should be be EXTENDED when the slim page will be reviewed completely against jade page

Agreed. And we also want an automated test (ideally using asciidoctor-doctest) so that we can be confident that they never fall out of alignment once we get them aligned.

**Comment by cmoulliard** [comment]
@mojavelinux : Do you target a new github project to manage asciidoctor-doctest ?

**Comment by obilodeau** [comment]
Please enlighten me, how is this issue different than #63?

>  Do you target to create a new github project to manage asciidoctor-doctest ?

I only started to look into this so I might be wrong but I don't think that's necessary. This project will be _using_ the -doctest project to render test cases and compare them with hardcoded HTML of the expected output which should be stored here. There's already an issue for that work, see #92.

**Comment by cmoulliard** [comment]
> how is this issue different than #63?

This issue only covers the document.jade file. FYI : @Mogztter has fixed the issue with the revealjsdir attr in a separate PR

**Comment by mojavelinux** [comment]
@obilodeau #63 and #104 appear to be duplicates. Since #63 is the more active issue, I think any new information should be moved there and this should be closed as a duplicated.

Btw, we don't need a new github project to manage asciidoctor-doctest. It already has one. https://github.com/asciidoctor/asciidoctor-doctest It may need updates to accommodate what we want to do (or maybe it doesn't), but it should be addressed there.

**Comment by obilodeau** [comment]
> * Support attr - asset_uri_scheme, revealjs_customtheme, iconfont-name
> * Slim reference FontAwesome 4.3 while jade 4.4.

Adding these to #63. Closing this as duplicate.

**Comment by cmoulliard** [comment]
Can you please add the name of the file where the points should be resolved (= document.jade) @obilodeau ?

**Comment by obilodeau** [comment]
@cmoulliard done
