### ISSUE TITLE
Including custom Javascript

### ISSUE THREAD

**Issue by ginkel** [asciidoctor/asciidoctor-reveal.js#112]
Hi,

this is more of a question than an issue, but is there a way to include custom Javascript (e.g., analytics) with the slides generated using asciidoctor-reveal.js?

Thanks,
Thilo

**Comment by mojavelinux** [comment]
Yep. You should use docinfo. See http://asciidoctor.org/docs/user-manual/#docinfo-file

Note that there's a new way to declare the docinfo configuration that isn't yet reflected in the user manual. See https://github.com/asciidoctor/asciidoctor.org/issues/604 for details.

**Comment by ginkel** [comment]
Thanks for the speedy reply! I'm quite certain I tried that some time ago (but probably not using the new method), but I'll try again and keep you updated.

**Comment by mojavelinux** [comment]
I recommend the footer position.

**Comment by ginkel** [comment]
Works like a charm, thanks a lot! :-)

**Comment by mojavelinux** [comment]
:+1:
