### ISSUE TITLE
paragraph styles not translated in revelajs?

### ISSUE THREAD

**Issue by seinecle** [asciidoctor/asciidoctor-reveal.js#120]
I have:

`CAUTION: make sure you select the correct options`

It is passed through literally on the slides, instead of inserting an icon etc. Help?

Similarly, I plan on using the Graphviz filter: http://asciidoc.org/asciidoc-graphviz-sample.html

Is it supported in asciidoc-reveal.js?

**Comment by mojavelinux** [comment]
Yes, it should be working. Make sure you have the `:icons: font` attribute entry in the document header.

You won't be able to use the graphviz filter with Asciidoctor as the AsciiDoc filters aren't compatible with Asciidoctor. Instead, you'll want to use Asciidoctor Diagram to get the same functionality.

**Comment by seinecle** [comment]
Brilliant! Thanks!
