### ISSUE TITLE
package.json's "readme" not displayed on npmjs.com

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#124]
https://www.npmjs.com/package/asciidoctor-reveal.js says we have no readme but we have provided a readme in `package.json`.

Filed this upstream bug: https://github.com/npm/www/issues/136

**Comment by mojavelinux** [comment]
I can confirm that logic on npmjs.com has changed because we lost the README for Asciidoctor.js too. (See https://www.npmjs.com/package/asciidoctor.js). Thanks for reporting upstream.

**Comment by obilodeau** [comment]
We can specify both a markdown README and an AsciiDoc one. I think the one with most content will be displayed on github. I made a temporary README.md pointing to the proper doc and plugging AsciiDoc: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/README.md

Closing this. Will follow upstream bug.
