### ISSUE TITLE
null / "" are not mapped to false / true correctly?

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-reveal.js#125]
Having an issue (asciidoctor/asciidoctor-maven-plugin#288) with building slides from asciidoc with the Maven plugin, @mojavelinux pointed out that the plugin mapping of boolean values is correct but values are not mapped correctly by the reveal converter:

E.g., setting
```xml
<revealjs_controls>true</revealjs_controls>
```
leads to
```js
Reveal.initialize({
  // Display controls in the bottom right corner
  controls: ,
```
making JS complain about the , instead of an expected value of true or false.

This results in an empty slide show.

**Comment by mojavelinux** [comment]
The correct way to emit these values is as follows:

```
#{(attr 'revealjs_controls', '') ? true : false}
```

or

```
#{!!(attr 'revealjs_controls', '')}
```

(!! coerces the value to a boolean)

That way, the expression emits "true" if the attribute has a value (even if that value is empty string) and "false" if the value is nil or the attribute is not set.

**Comment by mojavelinux** [comment]
(we don't have to worry about converting the boolean to a string since the interpolation already takes care of that for us).

**Comment by mojavelinux** [comment]
This also shields us from being hit by other bogus values for these attributes.

**Comment by mojavelinux** [comment]
Actually, because we use default values, this isn't going to work since there's no way in what I proposed to set a false value.

That means we need the following:

```
#{(attr 'revealjs_controls', '') != 'false'}
```

**Comment by mojavelinux** [comment]
Default values for attributes are still a bit rocky in Asciidoctor, which is what is making this so difficult. There's also the legacy that true values are empty string. We're just jammed between a rock and a hard place on this one...so we have to do some extra work.

**Comment by obilodeau** [comment]
I don't understand what causes the issue. Can someone provide a simple example without the maven part?

**Comment by mojavelinux** [comment]
In AsciiDoc, empty string represents a "true" value. However, we are passing this value through "as is", thus causing the Reveal.js configuration to look like:

```
Reveal.initialize({
  // Display controls in the bottom right corner
  controls: ,
```

Instead, we should coerce the value to a boolean using a helper function. I've proposed a PR. See https://github.com/asciidoctor/asciidoctor-reveal.js/pull/126.

Here's how we now map the values:

```
true => true
false => false
nil => false
'true' => true
'false' => false
1 => true
0 => false
'1' => true
'0' => false
```

(technically, any other value is true).

**Comment by obilodeau** [comment]
Fixed pushed in master. Let me know if a release would simplify your workflow. I can make one.

**Comment by ascheman** [comment]
Thanks so far, can wait for the next release ...
