### ISSUE TITLE
Upgrade to Asciidoctor.js 1.5.6+

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#130]
Latest release: https://github.com/asciidoctor/asciidoctor.js/releases/tag/v1.5.6-preview.3

This release contains a lot of enhancements on the public API that should improve readability the Jade templates.

For instance:

```diff
-if node['$has_role?']('aside') || node['$has_role?']('speaker')
+if node.hasRole('aside') || node.hasRole('speaker')
```

**Comment by obilodeau** [comment]
Besides updating the README setup instructions, is there something else that needs to be done to "resolve" this?

**Comment by obilodeau** [comment]
This will be achieved within 1.1.0 release.

**Comment by obilodeau** [comment]
Some progress made, follow #143.

**Comment by obilodeau** [comment]
Done with the #156 merge
