### ISSUE TITLE
highlight.js missing from HTML output

### ISSUE THREAD

**Issue by kito99** [asciidoctor/asciidoctor-reveal.js#14]
I'm not sure what I'm doing wrong, but the output for my file does not include the highlight.js dependency. As far as I can tell, this should be there by default. I'm using reveal.js 2.62. These are the only dependencies I'm seeing:

 ```javascript
  dependencies: [
      { src: 'reveal.js/lib/js/classList.js', condition: function() { return !document.body.classList; } },
      { src: 'reveal.js/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
      { src: 'reveal.js/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
      
      { src: 'reveal.js/plugin/zoom-js/zoom.js', async: true, condition: function() { return !!document.body.classList; } },
      { src: 'reveal.js/plugin/notes/notes.js', async: true, condition: function() { return !!document.body.classList; } }
```

**Comment by danhyun** [comment]
What is the value of `source-highlighter` attribute? Asciidoctor documentation says to use `highlightjs` as the value here http://asciidoctor.org/docs/user-manual/#source-code-blocks
But the source code says it's looking for `highlight.js` https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/slim/document.html.slim#L130

**Comment by danhyun** [comment]
If you want to see a working example with Gradle reveal.js and highlight.js, see my example here https://github.com/danhyun/git-2015-session/blob/master/build.gradle#L79

Note I'm using my fork of reveal.js backend to use reveal.js 3.0.

**Comment by kito99** [comment]
Ah, so the correct value is:

:source-highlighter: highlight.js

Thanks, Danny.

Why does this contradict the manual?

**Comment by danhyun** [comment]
The manual expects value of `highlightjs` as noted here http://asciidoctor.org/docs/user-manual/#source-code-blocks

**Comment by kito99** [comment]
Yeah, but the manual says:

:source-highlighter: library value

Which implies the correct value is:

:source-highlighter: Highlight.js  highlightjs

Or am I just reading it wrong (perhaps it's clear to everyone else)?

**Comment by danhyun** [comment]
It's confusing, I thought that at first but it's really expecting one of [coderay, highlightjs, prettify, pygments].

Also this project does not recognize value `highlightjs`. It's looking for `highlight.js`, I've submitted a PR for this.

**Comment by mojavelinux** [comment]
The correct value is `highlightjs`. This is now clarified in the user manual (hopefully). Let us know if we need to make it clearer.

**Comment by bojanpopic** [comment]
The manual still talks about highlight.js and not highlightjs both in the general section http://asciidoctor.org/docs/user-manual/#source-code-blocks and in highlight.js specific section http://asciidoctor.org/docs/user-manual/#highlight-js

**Comment by mojavelinux** [comment]
I've gone ahead and updated the user manual to standardize on the value `highlightjs`. Technically, `highlight.js` is still a valid value in core, but that we'll stop recommend its use. Thanks for pointing this out!
