### ISSUE TITLE
Fragments should be applicable to open blocks

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#140]
Right now using fragments (steps) in reveal.js is problematic if you are not using bullets

For example, there is no way right now to have fragments work in this case:

```asciidoc
== Title

index.aspx?p=admin
  
* aspx => .NET
* p = include a file? (p for page)
```

because there is more than one block

### Proposed syntax

Idea 1:

```asciidoc
[%step]
== Title

index.aspx?p=admin
  
* aspx => .NET
* p = include a file? (p for page)
```

would apply step to every underlying block.

Idea 2:

```asciidoc
== Title

[%step]
--
index.aspx?p=admin
  
* aspx => .NET
* p = include a file? (p for page)
--
```

Create an open block and apply role on it. In the template engine we will recognize and handle that behavior.

**Comment by mojavelinux** [comment]
I strongly encourage you to review what I did for the Bespoke converter as it considers each of these cases and more.

See https://github.com/asciidoctor/asciidoctor-bespoke#the-build-option

It would be good if we could align on a strategy.

**Comment by obilodeau** [comment]
Thinking about it, I think the first proposal is less of a good idea
because of vertical slides. Could cause behavior hard to anticipate.

**Comment by berney** [comment]
Is there a way to do `[%step]` with images? To have more and more images appear on the same slide as you move forward?

If I understand correctly only bullet points can be stepped.

In the revealjs project demo I see text can change color etc. I'm not sure if this is possible with asciidoctor-reveal.js

**Comment by slonopotamus** [comment]
See https://github.com/asciidoctor/asciidoctor-reveal.js/issues/347#issuecomment-591020899

**Comment by Mogztter** [comment]
Resolved in https://github.com/asciidoctor/asciidoctor-reveal.js/commit/a5eff900d53f90d27aed56c37ab9f3da7871b83c
