### ISSUE TITLE
asciidoctor.js support is currently broken

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#143]
We need to wait for upstream to release a new version with this fixed integrated: asciidoctor/asciidoctor.js#370

This issue blocks the 1.1.0 release since we have no javascript story without asciidoctor.js

Stack trace:
```
$ node asciidoctor-revealjs.js 

/home/olivier/src/asciidoc/presentation-asciidoctorjs-test/node_modules/asciidoctor.js/dist/asciidoctor.js:26264
              } else { throw $err; }
                       ^
Cache: uninitialized constant ThreadSafe::Cache
```

**Comment by mojavelinux** [comment]
We're almost ready for an Asciidoctor.js release. There's just one more issue to resolve. I'm going to try to get to it as soon as I can...this weekend looks probable.

**Comment by obilodeau** [comment]
No rush. I just opened the ticket to remember and tick checkboxes on the #131 PR :wink:

**Comment by mojavelinux** [comment]
FYI, I updated the PR that was holding back the release. We just need to settle another issue regarding the Opal upgrade and we should be good to go.

**Comment by Mogztter** [comment]
@obilodeau How do you generate the file `lib/asciidoctor-revealjs/converter.rb` in "Opal mode" ? In `Rakefile` we are using this condition:

```ruby
  generator = if :mode == :opal
    Temple::Generators::ArrayBuffer.new(freeze_static: false)
  else
    Temple::Generators::StringBuffer
  end
```

I've tried different syntax, but I'm unable to set `mode => :opal`

**Comment by jirutka** [comment]
This code snippet is wrong, `mode` should be a variable, not a symbol.

**Comment by Mogztter** [comment]
@jirutka I've moved this block and replaced `:mode` by `args[:mode]`, see https://github.com/asciidoctor/asciidoctor-reveal.js/pull/156/files#diff-52c976fc38ed2b4e3b1192f8a8e24cffR21
Not sure if this was the original intention but now I can run this task with `Rake::Task[CONVERTER_FILE].invoke(:opal)`

**Comment by jirutka** [comment]
Yes, but I eventually changed the approach for reasons I don’t remember right now, now I recommend this: https://github.com/jirutka/asciidoctor-html5s/blob/opal/Rakefile.
