### ISSUE TITLE
Release 1.1.0 not in npmregistry

### ISSUE THREAD

**Issue by dschulten** [asciidoctor/asciidoctor-reveal.js#161]
Looking for 1.1.0 in https://www.npmjs.com/search?q=asciidoctor-reveal.js gives me:

1 packages found for "asciidoctor-reveal.js"
asciidoctor-reveal.js obilodeau
A Reveal.js converter for Asciidoctor and Asciidoctor.js. Write your slides in AsciiDoc!

1.0.4

**Comment by obilodeau** [comment]
I couldn't manage to finish the release process yesterday evening I had issues with the ruby package. I just finished and packages have been pushed out for both RubyGems and NPM.

**Comment by dschulten** [comment]
💯
