### ISSUE TITLE
Sourcecode highlighting with highlight.js is broken with Asciidoctor.js (node) in 1.0.4

### ISSUE THREAD

**Issue by dschulten** [asciidoctor/asciidoctor-reveal.js#162]
If the adoc has no option

    :source-highlighter: highlight.js

then sourcecode sections in slides will not be highlighted. Either please document that the option is required or make it the default.

Even with the above option highlighting is broken in 1.0.4, this line in document.jade:

    #{(node.$attr('source-highlighter') == 'highlight.js') ? "{ src: '#{revealjsdir}/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }," : ""}

resolves to:

    { src: '#{revealjsdir}/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },

i.e. the revealjsdir placeholder remains unresolved, it should be  `node_modules/reveal.js`. No idea if slim would resolve that properly.

**Comment by keenJoe** [comment]
the two options are required,right? 
`:source-highlighter: highlight.js`
`:source-highlighter: coderay`
 and although I resolved code in document.jade, there is no sourcecode highlight.

**Comment by dschulten** [comment]
Same problem in 1.1.0 when executing with [Javascript setup](https://github.com/asciidoctor/asciidoctor-reveal.js#node--javascript-setup)

**Comment by dschulten** [comment]
@keenJoe to fix source code highlighting with highlight.js in 1.0.4 you have to replace the above line in document.jade by:

    { src: '#{revealjsdir}/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },

That way the condition which checks if source-highlighter is highlight.js does not apply, the block will be written and the revealjsdir placeholder will resolve to node_modules/reveal.js.

In 1.1.0 the problem is different, I am still analyzing.

**Comment by obilodeau** [comment]
It probably never worked. Asciidoctor.js / node didn't get very far and didn't have many users.

I'm not going to backport a fix in 1.0.x since there are many other things broken with the jade templates. Thanks for PR.
