### ISSUE TITLE
Error: Cannot find module 'asciidoctor.js'

### ISSUE THREAD

**Issue by dschulten** [asciidoctor/asciidoctor-reveal.js#164]
Following the 1.1.0 readme for Javascript, I get:

    Error: Cannot find module 'asciidoctor.js'

When running `node asciidoctor-reveal.js`. Note: I am using npm 5 (flat _node_modules_ structure)

Solution: run

    $ npm i asciidoctor.js --save

I wonder if asciidoctor-reveal.js should better name an explicit asciidoctor.js dependency. Currently I get the `asciidoctor.js@1.5.6-preview.4`, but I wonder if latest will always be the right choice.

**Comment by obilodeau** [comment]
I don't understand how this can happen because the dep is specified in package.json: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/package.json#L45

Have you run `npm i --save asciidoctor-reveal.js` in the same directory that you are trying to convert AsciiDoc to slides?

**Comment by dschulten** [comment]
I deleted node_modules and package-lock.json and started from scratch, now that 1.1.0 is in npmregistry, now the asciidoctor.js dependency is a top-level dependency and everything works fine. It could be that I had a package-lock.json from an 1.0.4 setup.
