### ISSUE TITLE
Prettify syntax-highlighter support

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#171]
Asciidoctor{.js} supports prettify as a syntax highlighter. It should be pretty straightforward to implement.

See
* [asciidoctor's html5 converter support](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L217)
* prettify project: https://github.com/google/code-prettify

**Comment by archiloque** [comment]
It seems that the prettify project is not maintained any more, and the prettify support is not mentioned on Asciidoctor's doc so people won't be encouraged to use it (even if the code supporting it is still available) => I suggest to close this issue

**Comment by mojavelinux** [comment]
I agree we should really put prettify behind us. It was never officially released and it lacks support for many modern languages. It's a dead end.

**Comment by Mogztter** [comment]
Alright, let's close this issue 🚪
