### ISSUE TITLE
lib/asciidoctor-revealjs/converter.rb missing in 1.1.0

### ISSUE THREAD

**Issue by Maurice-Mueller** [asciidoctor/asciidoctor-reveal.js#172]
Today, I updated the gem from 1.0.4 to 1.1.0 . I get the following error now:

```
LoadError: cannot load such file -- .bundle/gems/ruby/2.4.0/gems/asciidoctor-revealjs-1.1.0/lib/asciidoctor-revealjs/converter
/.bundle/gems/ruby/2.4.0/gems/asciidoctor-revealjs-1.1.0/lib/asciidoctor-revealjs.rb:5:in `require_relative'
.bundle/gems/ruby/2.4.0/gems/asciidoctor-revealjs-1.1.0/lib/asciidoctor-revealjs.rb:5:in `<top (required)>'
```

Indeed, the file converter.rb is missing (it exists in 1.0.4 though).

Btw, something is also wrong with the official website: http://asciidoctor.org/docs/asciidoctor-revealjs/ (but I don't know, if this issue tracker is the right one - therefor, I didn't post an extra issue here).

**Comment by obilodeau** [comment]
Wow, that's a pretty major mistake... Thanks for spotting! I'm going to release a 1.1.1 pretty soon then.

I filed the website issue here: asciidoctor/asciidoctor.org#759

**Comment by obilodeau** [comment]
v1.1.1 [has just been released](https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v1.1.1)!

**Comment by Maurice-Mueller** [comment]
Yeah, it's working now :)
