### ISSUE TITLE
undefined method prepend when rendering table

### ISSUE THREAD

**Issue by gquintana** [asciidoctor/asciidoctor-reveal.js#178]
I get this error
```
C:\Work\project\src\slides\node_modules\opal-runtime\src\opal.js:4993
      throw exception;
      ^
prepend: undefined method `prepend' for "class=\"tableblock halign-left valign-top\"":String
```

When I build a slide deck containing a slide with a table:
```
= Table 

== Section 

|==== 
|Name 
|Description 

|foo 
|This is foo 

|====
```

My node modules are:
```
`-- asciidoctor-reveal.js@1.1.1
  +-- asciidoctor.js@1.5.6-preview.4
  | `-- opal-runtime@0.11.0-integration8
  |   `-- glob@6.0.4
  |     +-- inflight@1.0.6
  |     | `-- wrappy@1.0.2
  |     +-- inherits@2.0.3
  |     +-- minimatch@3.0.4
  |     | `-- brace-expansion@1.1.8
  |     |   +-- balanced-match@1.0.0
  |     |   `-- concat-map@0.0.1
  |     +-- once@1.4.0
  |     `-- path-is-absolute@1.0.1
  `-- reveal.js@3.6.0
```

**Comment by Mogztter** [comment]
I think it's because we are using `String#prepend` in `templates/helpers`:

https://github.com/asciidoctor/asciidoctor-reveal.js/blob/b18f91747699985cbcc6235ae42662548b8f0947/templates/helpers.rb#L56

This method is not (yet) implemented in Opal, see https://github.com/opal/opal/issues/1753
In the mean time, I think we could replace this line with the following code:

```ruby
attrs_str = attrs.empty? ? '' : ' ' + attrs.join(' ')
```

**Comment by mojavelinux** [comment]
I totally agree.

**Comment by gquintana** [comment]
Great, thanks for the fix.
v1.1.2 is tagged but package is not in NPM, is it a matter of time?

**Comment by mojavelinux** [comment]
I think @obilodeau said that he was unable to run the release because the build is currently failing on his machine. Once he gets that sorted out, then he'll probably notify us.

**Comment by mojavelinux** [comment]
It looks like there's a change in Ruby 2.5 that's resulting in a syntax error in the generated converter code. This doesn't surprise me as Ruby 2.5 seems to have broken things in temple.

@obilodeau I recommend releasing from Ruby 2.4 for now, though obviously we'll have to sort out this syntax error if it affects users with 2.5.

**Comment by obilodeau** [comment]
@gquintana version 1.1.3 was just released. Can you try it, please?

**Comment by gquintana** [comment]
Perfect. Thanks @obilodeau
