### ISSUE TITLE
[%notitle] not applied in first level title

### ISSUE THREAD

**Issue by gquintana** [asciidoctor/asciidoctor-reveal.js#182]
The `[%notitle]` directive doesn't work when applied on document title.

Example:
```
[%notitle]
= Level 1

Title is shown :-(

[%notitle]
== Level 2

Title is hidden :-)
```

The title "Level 1" is shown, while the title "Level 2" is hidden.

Tested on v1.1.3

**Comment by obilodeau** [comment]
You need to use the `:notitle:` [document attribute](http://asciidoctor.org/docs/user-manual/#header-summary). However, it completely removes the whole title slide (not just the title) so to accomplish your example it would look like this:

```asciidoc
= My Awesome Talk
:notitle:

[%notitle]
== First slide

Title is hidden :-)

[%notitle]
== Second slide

Title is hidden :-)
```

I just tested it, it should work.

**Comment by gquintana** [comment]
Thanks, it's a bit counter intuitive but it's OK.
Your trick is worth a mention in the doc https://github.com/asciidoctor/asciidoctor-reveal.js#slides-without-titles

**Comment by obilodeau** [comment]
For people familiar with AsciiDoc this is not counter-intuitive, quite the opposite: a level one title is a document title (not a section title) and a document is altered by using document attributes (see the link I pointed to earlier). You cannot have more than one "level one" title per document.

I'll add a note to the README.
