### ISSUE TITLE
video play enhancement: both video block and background-video options not great

### ISSUE THREAD

**Issue by alperyilmaz** [asciidoctor/asciidoctor-reveal.js#184]
Hi,
I'm trying to playback a webm video and having trouble getting best results. When I include the video by:

```adoc
[%notitle]
== Video test

[.stretch]
video::screencast-20171110.webm[]
```

The video element does not cover most of the silde even though `[.stretch]` has been applied. The screen shot below should give an idea about the white space.

![screenshot from 2018-02-19 05-29-02](https://user-images.githubusercontent.com/410615/36360530-f6aea3c8-1535-11e8-868e-4ad9178337f2.png)

 When I play the video as background, the result is perfect:

```adoc
[background-video="screencast-20171110.webm",options="controls,muted,notitle"]
== video file, options
```

except one caveat, the video starts playing right away (autoplay) and I can not pause the video since no controls have been shown. I tried `controls` option since HTML `<video>` element accepts `controls` option but it didn't work. It looks like the author of Reveal.js has [intentionally left out that option](https://github.com/hakimel/reveal.js/pull/1512), but in my case, I had to right click on video, turn on controls and then pause the video, I had several videos in the presentation. Although background videos are meant to non-interactive, it's quite obtrusive in my case. 

So, how can I have large videos in a slide which will not autoplay? My last resort is; uploading the videos to youtube and then playing them within iframe with youtube controls on, but it's kind of impractical.

**Comment by obilodeau** [comment]
Have you made any progress or found a workaround?

**Comment by obilodeau** [comment]
It could be a reveal.js limitation. `stretch` doesn't cover the whole screen, it maximizes in the canvas.

What is the resolution of your video and your `revealjs_width` and `revealjs_height` attributes values? Default are: 960x700 which is very square-ish and could be why it's not maximized.

**Comment by alperyilmaz** [comment]
I don't use `stretch` anymore, I usually add videos as background. You can close the issue if it's not effecting anybody else..

Thanks..
