### ISSUE TITLE
Numbering function: not possible with asciidoctor-revealjs?

### ISSUE THREAD

**Issue by antoinentl** [asciidoctor/asciidoctor-reveal.js#185]
It seems that asciidoctor-revealjs don't understand or implement [the numbering function of Asciidoctor](http://asciidoctor.org/docs/user-manual/#numbering): Asciidoctor offer to activate an automatic numbering of the sections with `:sectnums:`.

Is there a way to automatically number the sections in asciidoctor-revealjs?

**Comment by mojavelinux** [comment]
The converter is currently responsible for honoring the sectnums setting. You can see how this is done in the default HTML converter:

https://github.com/asciidoctor/asciidoctor/blob/1ad875c60f5847a5f70b23726197fc487bf3734b/lib/asciidoctor/converter/html5.rb#L324

The reveal.js converter would need to do something similar.

I am sort of curious what the use case is for numbering titles in slides. I didn't think that really applied in this context.

**Comment by antoinentl** [comment]
I use AsciiDoc, Asciidoctor, asciidoctor-pdf and asciidoctor-revealjs for course materials: I generate HTML presentations and PDF (and sometimes ODT with Pandoc) from the same AsciiDoc file. I need to numbering titles in my HTML presentations because my students are sometimes lost... It's useful for them when they take notes, they can refer to the course material (PDF or print) during a presentation. Maybe another way could be use, for example with a fixed element in the HTML presentation.

I will write an article about my use of this workflow in the coming months!

**Comment by mojavelinux** [comment]
Thank you for clarifying that use case. That indeed makes sense. I was not considering the case of slides for a training.

It's very feasible to add support for the section number feature to this converter. There may be some edge cases we have to consider, but basic support should be straightforward to add.

**Comment by obilodeau** [comment]
Interesting use case @antoinentl. Let us know when your article is published. I'm curious about the multi-backend users. How easy or ugly it is to try to support several different output medias.

**Comment by eiswind** [comment]
I see the same issue with my students. Would be great to have sect-nums in revealjs. There is always someone who gets lost...

**Comment by eiswind** [comment]
I'll see if I can create a PR. I'm not so much into Ruby at last.... :)

**Comment by obilodeau** [comment]
https://github.com/asciidoctor/asciidoctor-reveal.js/blob/7e53bd926c11b5cf68a7c4960afca3fd8bee8679/templates/section.html.slim#L59

As you can see this is [slim templates code](http://slim-lang.com/) with inlined ruby.

I would drop with a debugger here (instructions in `HACKING.adoc`) and see what is exposed by Asciidoctor's core. Is section.num already provided? If so then it would be little ruby and mostly slim templating.

**Comment by eiswind** [comment]
OK. I really had a tough time getting all the ruby stuff working :)

I created https://github.com/asciidoctor/asciidoctor-reveal.js/pull/317

**Comment by obilodeau** [comment]
Fixed in master with the merger of #317. It will be part of our next feature release.

**Comment by antoinentl** [comment]
A big thank you to both of you @eiswind and @obilodeau! It's perfect :+1:

**Comment by eiswind** [comment]
@antoinentl I'll do a first run with my students very soon. Let's hope they appreciate it :)
