### ISSUE TITLE
Center only the title page

### ISSUE THREAD

**Issue by robaca** [asciidoctor/asciidoctor-reveal.js#186]
I try to create a theme which shows regular pages aligned to the top, but the title page should be centered vertically. 

I disabled centering via 
```
= My presentation
:revealjs_center: false
```
But I found o way to tell the renderer to center only the title page. Using the role tag `[.center]` on the main title does not work. Adding a `:role: center` attribute again centers all slides.

**Comment by mojavelinux** [comment]
You can reverse the role setting after setting it in the document header.

```
= My presentation
:role: center

:!role:

== Next Slide
```

This may not be the most elegant solution, but something worth trying.

**Comment by robaca** [comment]
It's working! Thx

**Comment by Jasper-Li** [comment]
@mojavelinux 

I used saved these as file test.adoc. The second slide is still `vertical centered.`

```
= My presentation
:role: center

:!role:

== Next Slide
```

Runtime is bellow:

```
# bundle exec asciidoctor-revealjs  --version
Asciidoctor reveal.js 5.1.0 using Asciidoctor 2.0.20 [https://asciidoctor.org]
Runtime Environment (ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]) (lc:GBK fs:UT
F-8 in:UTF-8 ex:UTF-8)
```

**Comment by mojavelinux** [comment]
If you have questions about usage, please direct them to the users/asciidoctor-reveal.js stream in the project chat at https://chat.asciidoctor.org. The issue tracker is not a support portal.
