### ISSUE TITLE
reveal.js' stretch class and source/listing blocks doesn't work 

### ISSUE THREAD

**Issue by rakus** [asciidoctor/asciidoctor-reveal.js#195]
When the stretch class is applied to a source block, the block is not stretched on the slide.
```
[source,xml, role="stretch"]
----
some xml here
----
```
From my understanding it seems, that the resulting html is to deeply nested:
```
<div class="listingblock stretch">
    <div class="content">
        <pre class="highlight">
            <code data-noescape>
                some xml here
            </code>
        </pre>
    </div>
</div>
```
Removing the two outer ``<div>`` results in proper display:
```
<pre class="highlight stretch">
    <code data-noescape>
        some xml here
    </code>
</pre>

```

A similar problem was reported for images in #82

**Comment by refaelsh** [comment]
Just wanted to point out that the [documentation](https://asciidoctor.org/docs/asciidoctor-revealjs/#stretch-class-attribute) says to use the `stretch` thingy like this:

```
[.stretch]
```

And @rakus used it differently. What am I missing please?

**Comment by obilodeau** [comment]
@refaelsh, roles are an important part of AsciiDoc and they have two syntaxes, a quick one to save typing time and a more verbose one. You can learn more about it here: https://asciidoctor.org/docs/user-manual/#role

**Comment by mojavelinux** [comment]
Unless you have really good reason not to, you should always prefer the shorthand syntax (e.g., `[.stretch]`).

**Comment by refaelsh** [comment]
I understand. Thank you.
