### ISSUE TITLE
role=right on image block's behavior could be improved 

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#197]
Odd corner case I faced today. I usually do floating images this way:

```asciidoc
== Slide Title

* Some
image:ego-market_paper_cover.png[role=right,width=200px]
* Points
* I'm trying
* To make
```

But in this case it is ugly:

![imagespan-role-right](https://user-images.githubusercontent.com/546325/41363988-4ba189dc-6f03-11e8-8920-5b69cab2bd4a.png)

So trying various things, I think applying a role=right on an image block *above* the main slide content should do what I want (and be expected behavior for people familiar with html/css).

```asciidoc
== Slide Title

image::ego-market_paper_cover.png[role=right,width=200px]

* Some
* Points
* I'm trying
* To make
```

This gives:

![imageblock-role-right-now](https://user-images.githubusercontent.com/546325/41364073-917cf158-6f03-11e8-9541-75e9eb5978df.png)

But it's because there is no CSS instruction for role=right. I manually added one:

![imageblock-role-right](https://user-images.githubusercontent.com/546325/41364106-a557223e-6f03-11e8-9955-0e6d3e2762cd.png)

This is I think what we want. Thoughts?

**Comment by mojavelinux** [comment]
Yes, as much as possible we should control behavior using designated roles. That way, we maintain the right semantic abstraction.

**Comment by joaocmendonca** [comment]
Hey @obilodeau could you please post your custom css here? thx!

**Comment by obilodeau** [comment]
@joaocmendonca its:
```css
.reveal div.right {
        float: right;
}
```

I'm looking at pushing this in the code right now.
