### ISSUE TITLE
docinfo.html is not inserted

### ISSUE THREAD

**Issue by timothypratley** [asciidoctor/asciidoctor-reveal.js#198]
Expected:
Including a docinfo.html file and a :docinfo: shared attribute should cause it to appear in the html output.

Actual:
HTML is not inserted.

Workaround:
I am able to `ln -s docinfo.html docinfo-header.html`
Then the html is inserted into head.
i.e.: file must be called docinfo-header.html to be inserted, which contradicts the documentation in asciidoctor user manual.

I discovered this workaround on observing that the code is looking for header here:
https://github.com/asciidoctor/asciidoctor-reveal.js/blob/6d700b903e52bd57e9aa9f8f477e1ecff859b7ab/templates/document.html.slim#L72

There is related and conflicting information here:
https://github.com/asciidoctor/asciidoctor/issues/1510

My repo demonstrating the problem:
https://github.com/timothypratley/enterprise-clojure-training

**Comment by mojavelinux** [comment]
Please see https://github.com/asciidoctor/asciidoctor-bespoke/blob/master/templates/slim/document.html.slim for the correct way to support docinfo in the reveal.js converter. Specifically:

```
        - unless (_docinfo = docinfo :header, '-reveal.html').empty?
          =_docinfo

...

        - unless (_docinfo = docinfo :header, '-reveal.html').empty?
          =_docinfo

...

      - unless (_docinfo = docinfo :footer, '-reveal.html').empty?
        =_docinfo
```

I believe we should look for the `-reveal.html` qualifier to avoid conflicting with the docinfo file used for the HTML output. wdyt?

**Comment by timothypratley** [comment]
According to https://asciidoctor.org/docs/user-manual/#naming-docinfo-files conflicts can be avoided by using the `private` naming scheme. Thus if I wanted to have a docinfo only apply to slides I would call it `slides-docinfo.html` and set the `:docinfo: private` attribute. I think that when `:docinfo: shared` is set then `docinfo.html` should be included in the slides head.

Right now I am using `docinfo.thml` as a shared location to set a favicon that is used in both slides output and a book/manual output. I can see that sometime you would want to include javascript specific to the slides.

I am new to asciidoctor and .slim so my apologies if I am misunderstanding. I'm very grateful that it is capable of so many things. Just raising the issue to improve the ability of new users to make use of it :)

**Comment by mojavelinux** [comment]
> According to asciidoctor.org/docs/user-manual/#naming-docinfo-files conflicts can be avoided by using the private naming scheme. Thus if I wanted to have a docinfo only apply to slides I would call it slides-docinfo.html and set the :docinfo: private attribute.

That's still not sufficient to support the goal of a single source document. Some users want to be able to generate an article and slides from the same document. But the docinfo file wouldn't be able to tell the difference.

What we could do is introduce the idea of a docinfo qualifier. The reveal.js and bespoke converters would set this by default, but it would still be possible to nullify it using at attribute assignment. That would give us the best of both worlds.

**Comment by mojavelinux** [comment]
To clarify, you are absolutely right to raise this issue. I'm simply suggesting that we bring the behavior into alignment with the bespoke converter.

**Comment by timothypratley** [comment]
I see. Yes, that sounds perfect! :)
