### ISSUE TITLE
Allow slide title to be hidden using option

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-reveal.js#20]
In addition to recognizing the `!` as an anonymous slide (a slide with no title), we should also allow the title to be hidden. This way, the title can be part of the semantics of the document and present in the slide notes, but hidden from presentation mode.

One way is to allow the use of the `notitle` option:

```
[%notitle]
== Title not shown

content
```

Another is to recognize a title that begins with `! `.

```
== ! Title not shown

content
```

The first option is more semantically correct. The second might be useful in a pinch.

**Comment by obilodeau** [comment]
+1

The ! should be kept as it is less typing. And it should be documented
also...

**Comment by kubamarchwicki** [comment]
My take towards `[%notitle]` would be as simple as this https://github.com/kubamarchwicki/asciidoctor-reveal.js/blob/e38c5dd89b0bea9e6e3c4889d18338bc98f320c1/templates/slim/section.html.slim#L6 

I think option should be only used to toggle title display (h2 tag) - the section id attribute should be displayed (as it can be used for additional, page specific styling)

What you think? This is my first step into slim templates and backends in general :)

**Comment by mojavelinux** [comment]
Exactly how I was going to implement it. I think there's still a question whether it should be `%notitle`, `%hide-title` or both. But I'm open to input.

**Comment by obilodeau** [comment]
If there is a title but it is not shown then %hide-title seems the more semantically correct value.

**Comment by mojavelinux** [comment]
+1

I think we should proceed with that idea, unless someone can think of a
shorter way to express it.

**Comment by bug** [comment]
Any progress on implementing that?

**Comment by bug** [comment]
BTW, isn't the noheader attribute supposed to do exactly that? (http://asciidoctor.org/docs/user-manual/#header-summary)

**Comment by obilodeau** [comment]
@bug I believe `noheader` is for the document header (in reveal.js' case the html headers).

Your link made me realize that `notitle` already exists as an asciidoctor header attribute. This means that we should probably go with `%notitle` instead of `%hide-title` then. Principle of least surprise.

**Comment by mojavelinux** [comment]
In the Bespoke.js converter I decided to use the option name "conceal". I'd
be open to both conceal and notitle.

As for noheader, I decided to use that attribute as a way to disable the
automatic title slide. The global notitle attribute is yet unused in this
context.

**Comment by obilodeau** [comment]
If someone can review the pull request and ACK it, I'll merge it.

It worked on my setup. Try to render example `test/concealed-slide-titles.adoc` for an easy assessment.
