### ISSUE TITLE
Image and text paradigma

### ISSUE THREAD

**Issue by moovida** [asciidoctor/asciidoctor-reveal.js#200]
Hi, in my slides I am using very often an image and at the side of the image a bullet list or some other text. I am trying to get this with a table.

I am using: 

```
[cols="<.<,<.<"] 
|=== 

a| 
1. connect your Android device to internet 
2. open Play Store 
3. type geopaparazzi within the Search textbox 
a| image:images/01_install.png[width=70%] 

|=== 
``` 

I would expect a bullet list on the left and an image on the right. 

Which is indeed what happens, but the bullet list is aligned at the center of the image. I have tried almost everything with the alignments settings but have not been able to get out of this. 

Since in asciidoctor html this behaves correctly, I signal it here as possible issue. 
Is there anything that can be doen to achieve this?

**Comment by obilodeau** [comment]
We have not pulled in the CSS required to accomplish this from the asciidoctor project. This is tracked by #77.

As a workaround, you can most likely get away with it using `role=right` in your image attributes like this:

```asciidoc
. connect your Android device to internet
  image:images/01_install.png[width=70%,role=right]
. open Play Store 
. type geopaparazzi within the Search textbox
```

In the future, I think we'll make table behave like tables (for content, not for display) but I'll make and document a set of standard roles for the common use cases of slides (i.e.: bullets on the left, image/chart on the right, etc.).

**Comment by moovida** [comment]
Ouch, I missed this answer, thanks though.

Just as an info, the workaround you mention doesn't do the trick.

**Comment by Mogztter** [comment]
With the latest version, you should be able to use grid layout instead: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/CHANGELOG.adoc#400-2020-02-18

Is there anything more to do regarding this issue?

**Comment by moovida** [comment]
Thanks for this @Mogztter .

I will close this issue as it is outdated.
