### ISSUE TITLE
Further improvements to reveal.js plugin configuration.

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#201]
As said in #196, summarizing here:

reveal.js notes plugin doesn't work when loaded from a CDN. It would be preferable if the newly introduced `:revealjs_plugins:` attribute would override a reveal.js plugin configuration instead of appending to it. This way the notes plugin could be replaced with a local version that should work even if reveal.js is loaded from a CDN.

Original PR provider didn't have time to implement and do the proper test. On my end, I'm going to prioritize other things first but I wanted to track it down.

**Comment by a4z** [comment]
I think I have an idea how to realize this.
I do not mind caring about tests, but until now I do not know how the testing works for this project.
All this infrastructure is pretty new for me, but looking at the HACKING.adoc the first time now, so I hope the next change comes with tests ;-)
But please note that I am back at work after several weeks holiday and have a very very young daughter at home, so please do not expect results too fast

**Comment by a4z** [comment]
solution suggestion in PR #204 , please review and share you thoughts

**Comment by a4z** [comment]
Hi @obilodeau , please review and comment
as in the PR stated, where I am mostly talking with myself, all plugins can now be turned off, or on.

the default behaviour is as it was, tests are passing, 

before adding tests for all the toggles, what is, depending on how much work someone wants to invest, pretty much work, (5 flags in all combinations, but we do not need to go that deep), I would like to have feedback if this is an accepted solution.

**Comment by a4z** [comment]
Thank you for the awesome improvements you did! 
Can't await switching my current slides to the new master, what I will do from next week on
