### ISSUE TITLE
Support fragmentInURL option

### ISSUE THREAD

**Issue by MateuszKubuszok** [asciidoctor/asciidoctor-reveal.js#206]
Reveal.js supports `fragmentInURL: true|false` option which:

```
	// Flags whether to include the current fragment in the URL,
	// so that reloading brings you to the same fragment position
	fragmentInURL: false,
```

it is quite useful if one configure its gulp that on `presentation.adoc` it should generate `presenation.html` which in turn refreshes browser in (`npm serve` default behavior). This way, one can have real life preview of the presentation.

I found no way of passing such option from asciidoctor in the documentation, thus a feature request.

**Comment by a4z** [comment]
oh, interesting! since I use to write with life reload enabled, this seems to be exactly the feature that I miss.
this would spare me me workarround with using include files to always have just a hand full of slides active and quickly go to the edited one after reload
need to look this up

**Comment by a4z** [comment]
implementing this should be simple, 
also need to research what `pdfSeparateFragments` attribute does, maybe that's related and should be added in the same PR.

when - sooner or later - I get feedback from @obilodeau on #204 and this is done, and I find the next time slot, I could have a look at this if on one else add it until than
