### ISSUE TITLE
Sync with reveal.js 3.7.0

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#208]
Upstream reveal.js added many new options, some of which were already requested by users (see #206): https://github.com/hakimel/reveal.js/releases/tag/3.7.0

**Comment by bcouetil** [comment]
I'm using reveal.js 3.7.0 with current master branch of asciidoctor-reveal with no issue. Is this still open ?

**Comment by obilodeau** [comment]
Revealjs 3.7 works just fine with our project. What needs change is to
enable the new features offered by revealjs' configuration. This issue
tracks this.
