### ISSUE TITLE
Load highlight.js from a CDN

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-reveal.js#21]
Load highlight.js from a CDN like we do with the HTML5 output instead of using the bundled version. Of course, we can still recognize the property of highlightjs dir so that it's possible to use the bundled version, but we should be consistent with the HTML5 output by default.

**Comment by Mogztter** [comment]
I agree the version in the reveal.js plugin is outdated, see: https://github.com/hakimel/reveal.js/issues/2562

We should use a copy of https://github.com/hakimel/reveal.js/blob/master/plugin/highlight/highlight.js without highlight.js.

@obilodeau What do you think? The downside is that we will need to sync this file when we upgrade reveal.js.

**Comment by Mogztter** [comment]
Not sure about the CDN part, considering that we are using a local copy of reveal.js but otherwise :+1:

**Comment by obilodeau** [comment]
I was never particularly affected by this so I don't mind. I'll merge if it makes sense and the changes to the release process are documented.
