### ISSUE TITLE
Notes syntax seems to be broken

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor-reveal.js#210]
Hi all,

The notes syntax as stated in the [docs](https://asciidoctor.org/docs/asciidoctor-revealjs/#basic-presentation-with-speaker-notes) is broken, it does not work. It is stated there like this:
```
[.notes]
--
* tell anecdote
* make a point
--
```
What actually works is this:
```
[NOTE.speaker]
--
* tell anecdote
* make a point
--
```
I found it in the [example file](https://raw.githubusercontent.com/asciidoctor/asciidoctor-reveal.js/master/examples/speaker-notes.adoc) as stated in the docs.

**Comment by obilodeau** [comment]
The new note syntax was recently merged in https://github.com/asciidoctor/asciidoctor-reveal.js/pull/202. That work hasn't been released yet but if you look at GitHub's master branch you will see its documentation.

Looking at the documentation through the tag of the version you are using might be a way to avoid such problems: https://github.com/asciidoctor/asciidoctor-reveal.js/tree/v1.1.3#basic-presentation-with-speaker-notes

I'm going to close this ticket. Feel free to re-open if you have further related inquiries or comments.

**Comment by refaelsh** [comment]
I understand. Thank you very much.
