### ISSUE TITLE
Request: please add `data-trim` to the `<code>` tag

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor-reveal.js#211]
Hi all,
Please add the `data-trim` option to the `<code>` tag. It makes the code blocks bigger, and most importantly, it removes the scroll bar. I found this suggestion [here](http://wsmoak.net/2015/09/16/presenting-source-code.html).

Thanks. Refael.

**Comment by obilodeau** [comment]
I'll do some tests and see what we should do by default. Thanks for the suggestion!

**Comment by obilodeau** [comment]
I did some tests tonight and didn't see a difference. I realized just now that I was not using the latest reveal.js. I'll retry tomorrow evening with reveal.js 3.7.0. In the meantime, here's what the patch looks like:

```diff
diff --git a/templates/listing.html.slim b/templates/listing.html.slim
index b2ea93d..b652ed8 100644
--- a/templates/listing.html.slim
+++ b/templates/listing.html.slim
@@ -30,6 +30,6 @@
   - pre_class << 'listingblock'
   - pre_class << role if role
   pre class=pre_class lang=pre_lang id=@id
-    code data-noescape=code_noescape class=code_class =content
+    code data-trim=true data-noescape=code_noescape class=code_class =content
 - else
   pre class=(nowrap ? 'nowrap' : nil) =content
```

**Comment by obilodeau** [comment]
Couldn't get it to work. `data-trim` changes nothing here. Can you provide an example please (AsciiDoc source and screenshot)?

**Comment by mojavelinux** [comment]
According to that post:

> It's common to use the data-trim attribute on the <code> element to trim any surrounding whitespace.

Asciidoctor already trims the whitespace around the content of a listing block.

**Comment by refaelsh** [comment]
> Couldn't get it to work. data-trim changes nothing here. Can you provide an example please (AsciiDoc source and screenshot)?

Hmm... Feeling a bit embarrassed here. But I cant seems to reproduce it. Sorry guys. I remember it clearly, but cant reproduce currently. I will close this issue, and if I am able to reproduce, I will take screenshots immediately and re-open this issue.
