### ISSUE TITLE
Feature request: please add support for slide numbers

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor-reveal.js#212]
Hi all,

According to the [AsciiDoctor RevealJS docs](https://asciidoctor.org/docs/asciidoctor-revealjs/#reveal-js-options) I can use this:
```
:revealjs_slideNumber: true
```
But, in [RefaelJS docs](https://github.com/hakimel/reveal.js#slide-number), there are more options.
For example, I would like to do this:
```
:revealjs_slideNumber: c/t
```
Please add support for the above.

Thanks. Refael.

**Comment by obilodeau** [comment]
Reveal.js 3.7.0 introduced many new configuration options which we don't support already. We have an issue open about it: #208.

I'm going to keep this one open because I might forget that slideNumber is no longer only a true / false toggle.

**Comment by obilodeau** [comment]
Ok, I finally succeeded with the helper. I made a rookie mistake while debugging it. All I need is add more test cases and I'll have a PR soon.

**Comment by obilodeau** [comment]
Fixed with the merge of #239 into master. Will be part of the upcoming 2.0 release.
