### ISSUE TITLE
Sync to Asciidoctor.js' 1.5.9 (and matching Opal)

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#227]
We post-poned #187. It means we specify asciidoctor.js' dependency still. A major release means we should sync with the latest code.

Opal is only required as a devDep, make sure it's not pulled-in in ruby environments if we specify a special version in the Gemfile.

**Comment by codecholeric** [comment]
BTW: If I force `asciidoctor.js@1.5.6-preview.4` to be used, then `asciidoctor-plantuml` breaks within `opal` :frowning_face: 
So I guess those two versions are just incompatible...
Feels a little bit, like the plugin mechanism of asciidoctor.js should be improved somehow to not create a coupling via a specific version of a 3rd party lib...

**Comment by mojavelinux** [comment]
That's literally what we're working on right now. There's a whole bunch of improvements coming to these integration layers, underpinned by a switch to semantic versioning. This extension will obviously be a good test of how it's coming along.

**Comment by obilodeau** [comment]
In the meantime you can try to use the Ruby toolkit: Asciidoctor + [asciidoctor-diagram](https://asciidoctor.org/docs/asciidoctor-diagram/#installation)

**Comment by codecholeric** [comment]
Thanks @obilodeau, I've tried to get this to work with Gradle / JRuby, but I've failed as well with

* https://plugins.gradle.org/plugin/org.asciidoctor.jvm.revealjs
* https://github.com/asciidoctor/asciidoctor-gradle-examples/tree/master/asciidoc-to-revealjs-example

Maybe I'll try the plain Ruby stack in the end (or just use RevealJS with Markdown and generate the PlantUML statically, even if it's not as convenient)

**Comment by obilodeau** [comment]
What's the issue with the Java stack? If it's using jruby and
asciidoctor-diagram works with it then it should just work with revealjs
too.

**Comment by codecholeric** [comment]
With the new alpha version of the revealjs plugin I always either got something like "asciidoctorj is missing" or "can't add asciidoctorj as it is already present", no matter which combination I've tried.
With the second version I tinkered around for a while as well, but eventually stopped at

```
Passing through unknown backend: revealjs
(RuntimeError) Could not find a converter to handle transform: document
```

I really stripped the asciidoc down quite a lot and it should be the same as in the example, so I don't know (I saw an issue though in the example repo that had pretty much the same error message, don't know if it's related)
At the moment though I really need to create a presentation, so I'll just let it rest and look a little later, maybe when the asciidoctor-revealjs plugin comes out of alpha. For now I'm doing okay with markdown and statically rendered PlantUML...

**Comment by obilodeau** [comment]
Yeah, I totally understand how time sensitive is preparing a presentation. Quick hacks are *way* better than a slide-deck with no diagrams on the stage :laughing:

Once the release will be done let's look at this again but in another ticket because this ticket got side-tracked here.

Getting back on track, I will sync to Asciidoctor.js 1.5.9 and matching Opal in a PR that should be submitted soon.
