### ISSUE TITLE
Table not generated correctly when one column contain bullet list

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-reveal.js#23]
The following will not generate the source block.

```
[cols="2*"]
|===
a|
[source,groovy]
----
myTask {
    mySources file( 'path/foobar' )
    mySources new File( 'path2/foobar' )
    mySources 'file3', 'file4'
    mySources { "lazy evaluate file name later on" }
}
----
a|
* Allow ability to:
* Use strings and other objects convertible to `File`
* Append lists
* Evaluate as late as possible
* Reset default values
|===
```

If both columns contain a source block then both are generated.

**Comment by mojavelinux** [comment]
Are you sure the source listing isn't just flowing off the screen due to the text size of the itemized list? We could implement the vertical alignment in the reveal.js backend so that the code listing is pushed to the top. We'd need to add the following to a built-in stylesheet:

```
td.valign-top {
  vertical-align: top;
}
```

**Comment by wackywendell** [comment]
It looks to me like @mojavelinux is right on with the vertical-alignment issue. I removed a couple items from the list:

```asciidoc
== Table

[cols="2*"]
|===
a|
[source,groovy]
----
myTask {
    mySources file( 'path/foobar' )
    mySources new File( 'path2/foobar' )
    mySources 'file3', 'file4'
    mySources { "lazy evaluate file name later on" }
}
----
a|
* A list item
* Another list item
* A third list item
|===
```

Which gives this result:

![screen shot 2015-05-06 at 10 55 54 am](https://cloud.githubusercontent.com/assets/245071/7495864/974a5e16-f3de-11e4-8ad8-2460e28387b7.png)

With more list items (as given in the initial issue), I get this:

![screen shot 2015-05-06 at 10 59 46 am](https://cloud.githubusercontent.com/assets/245071/7495932/1db17aca-f3df-11e4-9f58-2e0428a8c8e7.png)

**Comment by obilodeau** [comment]
With current master, it's not pretty but it works:

![Selection_007](https://user-images.githubusercontent.com/546325/74079025-8a0fc980-49ff-11ea-868a-b83d70fa7cc9.png)

Since this is a really old ticket I'm just going to close it.
