### ISSUE TITLE
Using extension lab with reveal backend

### ISSUE THREAD

**Issue by bcouetil** [asciidoctor/asciidoctor-reveal.js#233]
Hello,

I'm blown away by the integration of c3js in html5 backend using a macro from the extension lab.

This does not render with the reveal backend at all, is it a separate dev needed, or do I have to configure it another way ?

**Comment by bcouetil** [comment]
In the mean time I found a solution : the body part was inserted, not the header. So I used docinfo-header.html, and now it works like a charm.

**Comment by a4z** [comment]
Can you please tell me what the extension lab is?
all I know is this https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware 
but there I can not find c3js there

**Comment by bcouetil** [comment]
Sure, it's the official Asciidoctor extension lab : https://github.com/asciidoctor/asciidoctor-extensions-lab

**Comment by a4z** [comment]
oh, thanks! ,this explains it why I could not find anything on reveal.js  about it :-)

**Comment by obilodeau** [comment]
Mixing back-ends and extensions probably works but I don't see any existing hooking points in the reveal.js back-end to be notified of adding specific headers. @mojavelinux does the Asciidoctor extension API supports that? Can you point me to a simple example of this working? That should be enough for me to look into it.

Also,

> In the mean time I found a solution : the body part was inserted, not the header. So I used docinfo-header.html, and now it works like a charm.

You should provide minimal working examples when you achieve something like that. This way others can benefit too.

This thing is all about helping everyone making pretty slides with AsciiDoc. Sometimes examples and docs is greater than code.

**Comment by bcouetil** [comment]
You are right, I was still digging back then. Here is what I obtained.

Downloaded the mentioned plugin and used it in my maven setup (and the `docinfo` attribute for the header fix) :
```
[...]
<configuration>
    <sourceDirectory>src/docs/asciidoc</sourceDirectory>
    <requires>
        <require>asciidoctor-diagram</require>
        <!-- block extension to include c3js (bar/line/step/spline) chartist (bar/line) chartjs (line) -->
        <require>./src/docs/asciidoc/lib/chart-block-macro.rb</require>
    </requires>
[...]
<attributes>
    <docinfo>shared</docinfo>
</attributes>
[...]
```
Here are 3 block of code, first one using the extension (with pie PR not yet merged : https://github.com/asciidoctor/asciidoctor-extensions-lab/pull/76/files), 2 other ones raw JS :

```
== Intérêt de la revue de code

[.title]
Que pensez-vous être la pratique d'entreprise décisive pour améliorer la qualité de code ?

[chart,pie]
....
Code Review,27
Unit Testing,19
Functional Testing,13
Continuous Integration,12
Integration Testing,9
Detailed Requirements,7
Static Analysis,3
Training/On-boarding,3
User Stories,2
Other,5
....
```
```
[.title]
Quels sont les plus grands bénéfices de la revue de code ? 

++++
  <div id="benefices"></div>
  <script type="text/javascript">
c3.generate({
  bindto: '#benefices',
  size: { height: 500, width: 1000 },
  data: {
    x: 'x',
    columns: [
        ['x','Amélioration de la qualité','Partage de connaissance','Amélioration de la maintenabilité','Progression des moins expérimentés','Adhérence aux standards'],
        ['Pourcentage',90,72,59,56,49]
    ],
    type: 'bar'
  },
  axis: {
    rotated: true,
    x: {
      type: 'category',
      tick: {
        rotate: -90
      }
    }
  },
  color: {
      pattern: ['#B11E3E','#444444','#D6D6B1','#53A3DA','#8DBF44','#9D145F','#FFE119','#000075','#E8575C','#56A29A']
  }
});
</script>
++++
```
```
[.title]
Expérience d'une équipe sur un projet antérieur

++++
  <div id="experience"></div>
  <script type="text/javascript">
c3.generate({ 
  bindto: '#experience',
  size: { height: 500, width: 1000 },
  data: {
    x: 'x',
    columns: [
      ['x', 'Profil idéal', 'Dev n°1','Dev n°2','Dev n°3','Dev n°4','Dev n°5','Dev n°6','Dev n°7','Dev n°8'],
      ['Expérience en java', 5, 5, 4, 0.5, 0.25, 0, 0, 0, 0 ],
      ['Expérience en CI-CD', 5, 0, 0, 0, 0, 0, 0, 0, 0],
      ['Présence sur la version', 5.5, 5.5, 2, 2, 5.5, 5.5, 2.5, 2.5, 2.5 ],
    ],
    type: 'bar',
    axes: {
      'Expérience en java':'y',
      'Expérience en CI-CD':'y',
      'Présence sur la version': 'y2'
    }
  },
  axis: {
    x: {
      type: 'category'
    },
    y : {
      tick: { 
        format: function (d) { return d+ " ans"; },
        values: [1, 2, 3, 4, 5]
      },
      label : 'Expérience'
    },
    y2: {
      show: true,
      tick: {
        format: function (d) { return d+ " mois"; },
        values: [1, 2, 3, 4, 5]
      },
      label: 'Présence'
    }
  },
  color: {
    pattern: ['#B11E3E','#444444','#D6D6B1','#53A3DA','#8DBF44','#9D145F','#FFE119','#000075','#E8575C','#56A29A']
  }
});
</script>
++++
```

For now, here is the block of the extension that I had to copy from the extension to the `docinfo-header.html` (later, I downloaded latest versions of d3js & c3js to have more up-to -ate versions and avoid browser blocking of suspicious code) :
```
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/c3/0.3.0/c3.min.css">
<script src="http://cdnjs.cloudflare.com/ajax/libs/d3/3.4.11/d3.min.js" charset="utf-8"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/c3/0.3.0/c3.min.js"></script>
<link rel="stylesheet" href="http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
<script src="http://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
```


And here is the result : 

![screenshot-c3js-pie](https://user-images.githubusercontent.com/42612335/50333312-47421800-0505-11e9-83f6-d90acbe732ba.jpg)
![screenshot-c3js-horizontal-bar](https://user-images.githubusercontent.com/42612335/50333313-47421800-0505-11e9-9f09-035d8b1bab46.jpg)
![screenshot-c3js-multi-y-axis-bar](https://user-images.githubusercontent.com/42612335/50333314-47421800-0505-11e9-84de-ca6232d53ffd.jpg)

**Comment by bcouetil** [comment]
The actual chart macro extension is actually too limitating (and very badly developed, even for Ruby newbie eyes), I've actually rewritten it from the ground for c3js only (which has, on its own, everything needed for chart-as-code).

**Comment by mojavelinux** [comment]
> and very badly developed, even for Ruby newbie eyes

Let's be respectful. You can promote your work, or call for improvements, without putting down the work of others. This type of criticism only discourages newcomers from participating. We're all learning, and if we want the community to succeed, we need to be each others mentors and champions.

**Comment by mojavelinux** [comment]
> I don't see any existing hooking points in the reveal.js back-end to be notified of adding specific headers.

docinfo is designed for extensions to inject code into the output. Technically, the insertion slots are up to the converter, so you can provide more than what the built-in HTML converter provides. They are simply named locations.

**Comment by mojavelinux** [comment]
I think it's past time for the chart macro to graduate from the extension lab. The lab is really meant to serve as a place for prototyping ideas to see if they work out. Once you start relying on an extension in any fashion, it really needs to be its own project.

In fact, the chart extension has been split out for Asciidoctor.js (https://github.com/Mogztter/asciidoctor-chart). However, I'd like to see one for Ruby since it's more portable.

**Comment by bcouetil** [comment]
I apologize, this was indeed disrespectful. I edited this out.

**Comment by mojavelinux** [comment]
Thanks for following up, @bcouetil. I look forward to seeing your improvements!

**Comment by Mogztter** [comment]
The chart extension has graduated from the extension lab and is now a dedicated project: https://github.com/asciidoctor/asciidoctor-chart

@bcouetil Feel free to submit pull request to improve the c3js integration.
