### ISSUE TITLE
2 column layout slide with different width and background colors

### ISSUE THREAD

**Issue by mrcasablr** [asciidoctor/asciidoctor-reveal.js#234]
I'm loving asciidoctor-reveal.js and having fun creating decent slides. I was wondering if I can create a slide in 2 column layout (rows or columns) with different colors. This would allow more flexibility and engaging experience

**Comment by bcouetil** [comment]
You can do pretty anything with pure CSS and asciidoctor tables. 

Can you be more specific ? colors of background ? or point us to some example you can't achieve ? 

Here is how I translate myself a "X versus Y" : 

![x-versus-y](https://user-images.githubusercontent.com/42612335/50683189-8007e400-1011-11e9-958c-49a45625cf34.jpg)

**Comment by mrcasablr** [comment]
@bcouetil  something like this - https://gitpitch.com/gitpitch/the-template?p=template/md/sidebar#/0/1

**Comment by bcouetil** [comment]
The asciidoc : 

```
[.divide]
== !

[.west]
4.

[.east]
Lorem ipsum dolor
```

The css : 

```
.reveal section.divide {
  background: url(https://gitpitch.com/pitchme/cdn/github/gitpitch/the-template/master/2BC214532EFD788EA1527EA01A1B7203B570B0B726C4EA45DAAD639199D9C9CAA3442599C4E466CC86C00BB38F99D07F5EA9F00AC0EA65F4D88328DCCE97D33F9E0D061AE75622FE56127E209E6FA14B00E75C4181634B63AFA7C2ADF83DE974/template/img/bg/pink.jpg) #222;
  background-size: 30% 100%;
  background-position: left;
  background-repeat: no-repeat;
}

.reveal .west {
  position: fixed;
  font-size: 2em;
  top: 49%;
  left: 10%;
}

.reveal .east {
  position: fixed;
  font-size: 2em;
  top: 49%;
  right: 10%;
}
```

Et voilà 😄 

![two-colors](https://user-images.githubusercontent.com/42612335/50704854-23c8b280-1059-11e9-9a7a-1ac40e67d109.jpg)

**Comment by mrcasablr** [comment]
@bcouetil brilliant! :) Thank you, exactly what I was looking for and hopefully helps others too

**Comment by psteinb** [comment]
Just implemented this trick without the background image and colors. It works, but the individual items jump around. Meaning that when I transition upon the slide with `.east` and `.west`, I see the text items at the top of the page first. After a second or so, the pop to the vertical middle of the slide. Anybody else seeing this?

**Comment by mrcasablr** [comment]
I ran into it too, did not have the time back then. Would love to get this working.

I'm seeing this 
![Screenshot from 2019-06-15 00-04-42](https://user-images.githubusercontent.com/22866157/59530527-76a86f00-8f01-11e9-8bd1-caef5e7b4e74.png)

**Comment by bcouetil** [comment]
I'm not a css pro, but if you could point me to a public page with the problem, I would gladly try to help.

**Comment by obilodeau** [comment]
It's a question and there hasn't been activity in a while. Closing.

FWIW I'm about to open an issue about providing a shorthand syntax for a generic 2 column layout.
