### ISSUE TITLE
Typo: :imagedir: --> :imagesdir:

### ISSUE THREAD

**Issue by ghp-dev** [asciidoctor/asciidoctor-reveal.js#238]
Hi,
In the docs it reads:

> Background images file names are now relative to the **:imagedir:** attribute if set.

That did'nt work for me.

After setting the attribute :image**s**dir: in the document header, the image paths were correctly solved.

**Comment by obilodeau** [comment]
This was fixed in master last year. See #190.

You might see the outdated documentation if you check the documentation packaged with the last release but the [README on GitHub](https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/README.adoc) contains the fix.
