### ISSUE TITLE
TypeError: asciidoctorRevealjs.register is not a function

### ISSUE THREAD

**Issue by finp** [asciidoctor/asciidoctor-reveal.js#244]
Tried following the instructions in https://github.com/asciidoctor/asciidoctor-reveal.js#node-javascript-setup
but got the error in subject line.
Is node still supported?

**Comment by obilodeau** [comment]
You followed the documentation for master but you should be looking at the
documentation for our latest stable release. The node API changed.

There should be a link to the relevant documentation near the top of the
readme.

**Comment by finp** [comment]
Update: since 2.0 was released a few hours ago, everything works as expected, looks great,  closing
