### ISSUE TITLE
Slide navigation with mouse wheel with version 2.0.0

### ISSUE THREAD

**Issue by stenzengel** [asciidoctor/asciidoctor-reveal.js#249]
Hi,

Many thanks for your continuous and great work.

After installing version 2.0.0 of "asciidoctor-reveal.js" the slide navigation with mouse wheel does not work anymore. If I switch back to version 1.1.3, everything works fine.

I'm using the option `:revealjs_mouseWheel: true` at the top of the document.
Other options (e.g. `:revealjs_keyboard:`) work fine, i.e. can be enabled and disabled.
I have tested the mouse wheel with Firefox and Chrome.

The option `mouseWheel` still looks to be supported in the underlying "reveal.js" project (https://github.com/hakimel/reveal.js/#configuration)

Can you reproduce this behavior?
If you need further information, please don't hesitate to ask.

Best regards
Winfried

**Comment by bentolor** [comment]
Should be fixed on merging #237

**Comment by obilodeau** [comment]
This was fixed with the just-released 2.0.1 thanks to @bentolor's patch. Can you confirm that the fixed version works for you?

**Comment by stenzengel** [comment]
Yes, the error is fixed with version 2.0.1. Thanks @bentolor and @obilodeau!
