### ISSUE TITLE
Upgrade to Asciidoctor.js 2.0.0

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#252]
The final version is not yet available but I've published a second release candidate today. 
A few notes:

* The package was renamed to `asciidoctor`
* The package `asciidoctor` is now a meta-package that contains `@asciidoctor/core` and `@asciidoctor/cli`
* We probably should rename the package to `@asciidoctor/reveal.js-converter`
* We should make sure that the following is working:

```
$ npm i asciidoctor @asciidoctor/reveal.js-converter
$ asciidoctor -r @asciidoctor/reveal.js-converter -b reveal.js presentation.adoc
```

**Comment by mojavelinux** [comment]
> `@asciidoctor/converter-reveal.js`

When I come back to this with fresh eyes, the order strikes me as awkward. As much as the programmer in me wants it to be inverted, I think we should use `@asciidoctor/reveal.js-converter` instead.

**Comment by Mogztter** [comment]
If we want the following to be working, we will need to agree on an API.

```
$ asciidoctor -r @asciidoctor/reveal.js-converter -b reveal.js presentation.adoc
```

The reason is that the CLI will have to "automatically" register the converter.
We should also consider that we could register extensions:

```
$ asciidoctor -r @asciidoctor/reveal.js-converter -r @asciidoctor/plantuml-extension -b reveal.js presentation.adoc
```

In my opinion it's more intuitive than to require the user to create a JavaScript file to load and register the converters/extensions:

**init.js**
````js
require('@asciidoctor/reveal.js-converter').register()
````
```
$ asciidoctor -r ./init.js -b reveal.js presentation.adoc
```

**Comment by obilodeau** [comment]
> > `@asciidoctor/converter-reveal.js`
> 
> When I come back to this with fresh eyes, the order strikes me as awkward. As much as the programmer in me wants it to be inverted, I think we should use `@asciidoctor/reveal.js-converter` instead.

@Mogztter's PR I just merged didn't contain the package name change. Since this release is going to be a major one due to the Node API change, I suggest we change the package name right now if it still makes sense to do so.

Should this be renamed `@asciidoctor/reveal.js-converter` or did our mind change about that?

To me `@asciidoctor/reveal.js` would be even better since it is unlikely that we will ever have a non-converter reveal.js asciidoctor extension. I would be open to `@asciidoctor/converter/reveal.js` too. @mojavelinux's suggestion (`@asciidoctor/reveal.js-converter`) is also good btw, I was just trying to make it shorter.

**Comment by Mogztter** [comment]
> I just merged didn't contain the package name change. Since this release is going to be a major one due to the Node API change, I suggest we change the package name right now if it still makes sense to do so.

You're right.
I reverted my changes because I wasn't sure it will be included in a major release.

> Should this be renamed @asciidoctor/reveal.js-converter or did our mind change about that?
> To me @asciidoctor/reveal.js would be even better since it is unlikely that we will ever have a non-converter reveal.js asciidoctor extension.

I had the same thought and I think we can safely remove the extra `-converter` when the name is an output format (pdf, reveal.js, epub...).
In my opinion, `@asciidoctor/reveal.js` is concise, non-ambiguous and it reads well.

I will wait for @mojavelinux's approval to make sure that we are on the same page.

**Comment by obilodeau** [comment]
@mojavelinux: @Mogztter and I would go with `@asciidoctor/reveal.js` as the new module name for the javascript ecosystem for reasons stated above. The PR is ready (see #291). This is a breaking change and it will happen in what will become 3.0.0. We would like to move forward. Do we get your approval?

**Comment by mojavelinux** [comment]
> I had the same thought and I think we can safely remove the extra -converter when the name is an output format (pdf, reveal.js, epub...).

I think that's a reasonable and intutive assumption. I'll vote :+1: on `@asciidoctor/reveal.js`.

**Comment by obilodeau** [comment]
With #291 merged, now we probably need to do something on npm. Releasing an interim version of `@asciidoctor/reveal.js` like 3.0.0rc1 would probably make sense to reserve the spot and make instructions on the README work. Smoke tests probably need changes too.

**Comment by Mogztter** [comment]
> With #291 merged, now we probably need to do something on npm. Releasing an interim version of `@asciidoctor/reveal.js` like 3.0.0rc1 would probably make sense to reserve the spot and make instructions on the README work. Smoke tests probably need changes too.

I think it's a good idea 👍

**Comment by obilodeau** [comment]
Release candidate 1 packages are out there:  https://www.npmjs.com/package/@asciidoctor/reveal.js

**Comment by obilodeau** [comment]
I just tested the javascript API (which resulted in this PR #298 to update our Babel example API usage) and it works.

I also tested the README setup instructions:
```shell
npm i --save asciidoctor @asciidoctor/reveal.js
$(npm bin)/asciidoctor --version
$(npm bin)/asciidoctor -r @asciidoctor/reveal.js -b reveal.js README.adoc
```

And it worked.

This successfully completes all remaining tasks in this ticket. Closing.
