### ISSUE TITLE
Do we support the pdfSeparateFragments?

### ISSUE THREAD

**Issue by charleech** [asciidoctor/asciidoctor-reveal.js#256]
I would like to export the PDF  by printing all fragments, `[.step]`, in  the same slide.

Regarding to the [PDF Export](https://github.com/hakimel/reveal.js/#pdf-export), it mentions as the following:-

> If you prefer printing all fragments in their visible states on the same slide you can set the `pdfSeparateFragments` config option to `false`.

Do we support the `pdfSeparateFragments`?

**Comment by akosma** [comment]
Yes: open your slides on Chrome using the `?print-pdf&pdfSeparateFragments=false` options on the URL and you will be able to export all your steps in one slide.

**Comment by charleech** [comment]
Thank you. I'm able to export properly,
