### ISSUE TITLE
File extension is wrong on master

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#257]
When running the following command, it generates files with `.revealjs` extension instead of `.html`:

```
$ bundle exec rake examples:convert
```

I think it's related to: https://github.com/asciidoctor/asciidoctor/issues/891

**Comment by mojavelinux** [comment]
In Asciidoctor 2, it's necessary for a converter to specify the outfilesuffix explicitly. We no longer assume the outfilesuffix is .html. (Instead, the backend name is used to build the default outfilesuffix). Setting this trait is backwards compatible with 1.5.x.

However, when I check the converter I see:

```rb
basebackend "html" if respond_to? :basebackend
outfilesuffix ".html" if respond_to? :outfilesuffix
filetype "html" if respond_to? :filetype
```

So I'm confused why this is not working. Could you debug to see why this isn't getting set? Perhaps it has to do with the use of a composite converter.

**Comment by Mogztter** [comment]
I must admit I didn't check, I stumbled across this bug while working on Asciidoctor.js upgrade.

> So I'm confused why this is not working. Could you debug to see why this isn't getting set? Perhaps it has to do with the use of a composite converter.

Sure 👍

**Comment by Mogztter** [comment]
My bad, I was probably out of sync :disappointed:

**Comment by rquinio** [comment]
I also reproduced this behavior when upgrading from asciidoctor-revealjs 1.1.3 to 2.0.0
In my case it's
Setting the attribute outfilesuffix to ".html" allows to workaround:
https://github.com/rquinio/asciidoctor-maven-demo/blob/de9491c586debef52949d93bb31c67ff406ab688/pom.xml#L158-L159

**Comment by Mogztter** [comment]
@rquinio I encountered this issue while working on a local (out-of-synced) clone of this repository so I'm not sure it's related to your issue.

I think we should try to reproduce this issue with a simple test case.

**Comment by mojavelinux** [comment]
Btw, as a quick workaround, you can set the backend to `revealjs:html`. That sets the basebackend to .html instead of .revealjs. (See https://github.com/asciidoctor/asciidoctor/issues/3242 for reference).

I still don't see how this is happening though since the revealjs converter is set up correctly...unless for some reason you're using the templates directly without the composite converter.
