### ISSUE TITLE
Add options for presentation size

### ISSUE THREAD

**Issue by wackywendell** [asciidoctor/asciidoctor-reveal.js#26]
Reveal.js has 4 options related to [presentation size](https://github.com/hakimel/reveal.js#presentation-size), which I have found very useful for large screen / projector sizes where you can easily fit a big image and a few lines of text beneath it, by setting `width` and `height` to larger values. It would be useful to have at least those two options, and possibly also the `minScale` and `maxScale` options as well.

**Comment by mojavelinux** [comment]
+1

I think we can continue with the pattern of using the `revealjs_` prefix for these settings.
