### ISSUE TITLE
Setting revealjs_center has no effect

### ISSUE THREAD

**Issue by mjohenneken** [asciidoctor/asciidoctor-reveal.js#260]
Hello, 
I'm using asciidoctor-revealjs in conjuction with the asciidoctor-maven-plugin. I want to disable the `center` option of revealjs, but it just doesn't work. Other settings like width, height or setting mouseWheel are working fine.

If i set ` <revealjs_center>false</revealjs_center>` the output is `center: true`.

I already compared the spelling of the attribute to the [document.html.slim](https://github.com/asciidoctor/asciidoctor-reveal.js/blob/d6ad7daf2c4778dfaa5f7fe6de11e72aa8766034/templates/document.html.slim#L152) file. I tried diffrent asciidoctor-maven-plugin in vesion 1.5.6 and 2.0.0, asciidoctor-revealjs in version 2.0.0 and 1.1.3

Any ideas what could be wrong? 

My current config:
```
...//other stuff
<execution>
    <id>generate-slides</id>
    <phase>process-resources</phase>
    <goals>
        <goal>process-asciidoc</goal>
    </goals>
    <configuration>
        <outputDirectory>${project.slides.directory}</outputDirectory>
        <backend>revealjs</backend>
        <templateDir>${project.build.directory}/asciidoctor-reveal.js-${asciidoctor-revealjs.version}/templates</templateDir>
        <sourceHighlighter>coderay</sourceHighlighter>
        <attributes>
            <!--
                As we are downloading reveal.js in runtime, it sits in a nonstandard folder `reveal.js-${revealjs.version}`
            -->
            <revealjsdir>reveal.js-${revealjs.version}</revealjsdir>
            <!-- put here the reveal.js specific attributes -->
            <sourcedir>${basedir}/src/main/java</sourcedir>
            <revealjs_transition>linear</revealjs_transition>
            <revealjs_slidenumber>true</revealjs_slidenumber>
            <revealjs_theme>${presentation.theme}</revealjs_theme>
            <revealjs_title>${presentation.title}</revealjs_title>
            <revealjs_speaker>${presentation.speaker}</revealjs_speaker>
            <revealjs_company>${presentation.company}</revealjs_company>
            <!-- Fix aspect ratio to 16:9. Use px for size and positioning, reveal.js will scale to screen size. -->
            <revealjs_width>1728</revealjs_width>
            <revealjs_height>972</revealjs_height>
            <revealjs_history>true</revealjs_history> <!-- Remain at current slide on refresh -->
            <revealjs_center>false</revealjs_center>
            <project-version>${project.version}</project-version>
            <plantuml-config>${basedir}/src/theme/template/source/plantuml-config.txt</plantuml-config>
        </attributes>
    </configuration>
</execution>
```

Versions:

```
        <maven.compiler.source>1.6</maven.compiler.source>
        <maven.compiler.target>1.6</maven.compiler.target>
        <asciidoctor.maven.plugin.version>1.6.0</asciidoctor.maven.plugin.version>
        <asciidoctorj.pdf.version>1.5.0-alpha.16</asciidoctorj.pdf.version>
        <asciidoctorj.version>1.5.8.1</asciidoctorj.version>
        <asciidoctorj.diagram.version>1.5.10</asciidoctorj.diagram.version>
        <jruby.version>9.1.17.0</jruby.version>
        <revealjs.version>3.7.0</revealjs.version>
        <!-- Use 'master' as version and remove the 'v' prefixing the download url to use the current snapshot version  -->
        <asciidoctor-revealjs.version>2.0.0</asciidoctor-revealjs.version>
```

**Comment by bentolor** [comment]
I had similar issues which I'm trying to fix in #267 but those always involved uppercase letters in the attribute names

**Comment by obilodeau** [comment]
Have you figured it out? Maybe boolean values need to be handled as True / False instead of true / false? I'm not familiar with Maybe maven or asciidoctor-maven unfortunately.

**Comment by mjohenneken** [comment]
Not really, as i could not find the reason. I used css to work around the problem.  

 

Von: Olivier Bilodeau <notifications@github.com> 
Gesendet: Mittwoch, 4. Dezember 2019 07:43
An: asciidoctor/asciidoctor-reveal.js <asciidoctor-reveal.js@noreply.github.com>
Cc: Max Johenneken <max.johenneken@anderscore.com>; Author <author@noreply.github.com>
Betreff: Re: [asciidoctor/asciidoctor-reveal.js] Setting revealjs_center has no effect (#260)

 

Have you figured it out? Maybe boolean values need to be handled as True / False instead of true / false? I'm not familiar with Maybe maven or asciidoctor-maven unfortunately.

**Comment by obilodeau** [comment]
Unable to reproduce now that initial problem as been worked around.
