### ISSUE TITLE
Publish the generated converter class to the git tag

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-reveal.js#265]
I'm of the position that the generated converter class should be published to the git tag. In other words, all the source in the gem package should also be present somewhere in the repository. Otherwise, it looks like the gem package has code in it that isn't available (even though we know it's generated).

This would be done by committing the converter class prior to tagging the repository. It would make the tag divergent, but that's fine. What's important is that it matches the contents of the gem package (at least when it comes to the code).

**Comment by obilodeau** [comment]
Sounds very reasonable. Will document and do for 3.0.0.
