### ISSUE TITLE
Add support data-line-numbers from reveal.js

### ISSUE THREAD

**Issue by asm0dey** [asciidoctor/asciidoctor-reveal.js#266]
Currently reveal.js supports line highlighting in source code: https://github.com/hakimel/reveal.js/#line-numbers--highlights
Is it possible to support this feature in asciidoctor-revealjs?

**Comment by marcdexet-cnrs** [comment]
Hi.
I was previously using https://github.com/gnab/remark wich support a close feature just by adding an '*' in front of a code line.

It would be very useful for programing courses to be able to highlight particular line.

**Comment by mojavelinux** [comment]
We support a similar feature in Asciidoctor. See https://asciidoctor.org/docs/user-manual/#highlight-select-lines (so the framework is there). I'm sure it's possible to get it working in this converter. The converter can retrieve this information from the node, massage it, and pass it on to data-line-numbers.

(What's funny about this is that highlight.js refuses to support line number itself. If it did, this would be something Asciidoctor would already set up).

**Comment by marcdexet-cnrs** [comment]
I have been trying with coderay and pygments.
The most appectable is coderay with inline.

As for remarkjs, it uses a simple hack: a '*' put at the beginning of a line inject a specific css class to highlight the whole row.

It produces think of highlithed code: https://marcdexet-cnrs.github.io/devworkshop5_tips_for_maintainability/#136

**Comment by marcdexet-cnrs** [comment]
The `remark` syntax is

<pre>
.medium[We now can distinguish the **WHAT**...]

```python
*def check_propulsion_energy_against_duration(report, patrol_duration):

    average_energy_per_day = get_average_propulsion_energy_consumption_per_day()
    required_energy_level = patrol_duration * average_energy_per_day * SECURITY_COEFF + MINIMAL
    if required_energy_level > get_actual_stocked_energy() :
        report.register('propulsion_energy','NotEnoughEnergy', CRITICAL)
```
--

.medium[...from the **HOW**]
```python
def check_propulsion_energy_against_duration(report, patrol_duration):

*    average_energy_per_day = get_average_propulsion_energy_consumption_per_day()
*    required_energy_level = patrol_duration * average_energy_per_day * SECURITY_COEFF + MINIMAL
*    if required_energy_level > get_actual_stocked_energy() :
*        report.register('propulsion_energy','NotEnoughEnergy', CRITICAL)
```

</pre>

**Comment by mojavelinux** [comment]
Reveal.js uses highlight.js, which Asciidoctor already offers. This is a matter of configuring the integration in this converter. It's possible. The information needs to be passed from the AsciiDoc file to the HTML output. That's all.

**Comment by asm0dey** [comment]
Sorry, guys, I'm completely lost. If I've asked for something which asciidoctor-revealjs already offers — please close this task.

**Comment by mojavelinux** [comment]
Not at all. I'm just saying it's within reach to enable it.

**Comment by asm0dey** [comment]
Oh, got it, thanks

**Comment by marcdexet-cnrs** [comment]
I have produced lately a few courses about software dev good practices and I really missed this feature. It makes examples very clear.
How can I help to get this feature in the next release ?

**Comment by obilodeau** [comment]
`data-line-numbers` was added in reveal.js 3.8.0. See these issues #296 and #301 for more context about the milestone attribution I just did.

**Comment by obilodeau** [comment]
Support was merged in master minutes ago. Release soon.
