### ISSUE TITLE
Publish JAR

### ISSUE THREAD

**Issue by johnjelinek** [asciidoctor/asciidoctor-reveal.js#271]
Could you please publish this gem as something that can be brought in on the JVM? Seems like this has been done for some other backends:
* https://github.com/asciidoctor/asciidoctorj-epub3
* https://github.com/asciidoctor/asciidoctorj-pdf

**Comment by obilodeau** [comment]
I have no idea how to do this... Since this is volunteer work, I'm not interested in doing it either. I haven't written Java since University when gradle and maven didn't even exist (or were not popular). That said, if someone does the packaging and I only need to keep it current via simple updates, I'm willing to maintain it.

For the record, this is what happened with Asciidoctor.js support and Doctests. Someone else did it but I maintain it diligently. It can work. Are you willing to do the initial push?

**Comment by mojavelinux** [comment]
Generally, the translation to an AsciidoctorJ JAR is handled by the AsciidoctorJ team. As more extensions get redistributed this way, the process of automating those builds improves so they require very little minimal maintenance. Ideally, the release would happen automatically.

That being said, it's possible to use a gem without the extra packaging. The following example demonstrates how: https://github.com/asciidoctor/asciidoctor-maven-examples/blob/master/asciidoc-to-revealjs-example/pom.xml So it's inaccurate to say it *can't* be used on the JVM now.

**Comment by mojavelinux** [comment]
cc: @robertpanzer

**Comment by robertpanzer** [comment]
I can take care of that. 
I can’t give a timeline though, maybe I’ll get sth done over the holidays.

**Comment by mojavelinux** [comment]
Cool! The converter is popular enough that I believe the effort would be worthwhile.

**Comment by obilodeau** [comment]
> Generally, the translation to an AsciidoctorJ JAR is handled by the AsciidoctorJ team.

Once the initial packaging process is done (the scary, unknown part for me), I'm willing to attempt to send PRs to AsciidoctorJ to update the JAR. Just like I do to update asciidoctor.org website right now anyways.

I'm going to close this with these last words: If you need this, open an issue on the AsciidoctorJ repo.

**Comment by robertpanzer** [comment]
I already created a rep for that at robertpanzer/asciidoctorj-reveal.js. It’s just waiting for the transfer into the asciidoctor org

**Comment by mojavelinux** [comment]
Oh, I can help with that! You should be able to transfer now. Give it a try.

**Comment by robertpanzer** [comment]
Awesome, thanks. I’ll try it over the weekend

**Comment by robertpanzer** [comment]
I created a release candidate that can be used like this:
```xml
      <plugin>
        <groupId>org.asciidoctor</groupId>
        <artifactId>asciidoctor-maven-plugin</artifactId>
        <version>2.0.0-RC.1</version>
        <configuration>
          <backend>revealjs</backend>
          <requires>
            <require>asciidoctor-revealjs</require>
          </requires>
          <attributes>
            <imagesdir>${project.build.directory}/generated-docs</imagesdir>
            <revealjsdir>https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0</revealjsdir>
          </attributes>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>2.2.0</version>
          </dependency>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj-revealjs</artifactId>
            <version>3.1.0-rc.2</version>
          </dependency>
    <dependencies>
  </plugin>
...
    <profile>
      <repositories>
        <repository>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
          <id>bintray-asciidoctor-maven</id>
          <name>bintray</name>
          <url>https://dl.bintray.com/asciidoctor/maven</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
          <id>bintray-asciidoctor-maven</id>
          <name>bintray-plugins</name>
          <url>https://dl.bintray.com/asciidoctor/maven</url>
        </pluginRepository>
      </pluginRepositories>
      <id>bintray</id>
    </profile>
```

**Comment by obilodeau** [comment]
Should we add a reference to the [asciidoctor/asciidoctorj-reveal.js](https://github.com/asciidoctor/asciidoctorj-reveal.js) repo in our README as another installation option?

**Comment by robertpanzer** [comment]
Great idea!
Let's do this after I have released the first final version.

**Comment by robertpanzer** [comment]
Asciidoctorj-revealjs is now available at jcenter and at https://search.maven.org/artifact/org.asciidoctor/asciidoctorj-revealjs/3.1.0/jar

**Comment by johnjelinek** [comment]
I can't believe this day has finally come!

**Comment by obilodeau** [comment]
Request for comments on the PR with README adjustments: #337 

Last issue before 4.0.0 :crossed_fingers:
