### ISSUE TITLE
Option to disable generation of IDs for sections?

### ISSUE THREAD

**Issue by ebousse** [asciidoctor/asciidoctor-reveal.js#272]
Currently, this line:
https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/section.html.slim#L40

Means that each generated section looks like that (as soon as it has an `h1` title):
```html
<section id="_topic_slide">
```
Which then makes the URL of the slide look like that (when `history: true` in revealjs):
```
http://127.0.0.1:8080/#/_topic_slide
```
instead of this (when there is no `id`):
```
http://127.0.0.1:8080/#/1
```
---

Could we imagine an option to disable the systematic generation of an `id` for each `section`, in order to obtain URLs that are based on the slide number instead of the title of the slide? I find this very convenient when wanting to jump to a specific slide number. Also it reduces the size of URLs.

**Comment by Mogztter** [comment]
Hello @ebousse 

I think using `:sectids!:` should do the trick no? Could you please give it a try and report back?

**Comment by ebousse** [comment]
Indeed this works perfectly, thanks! I'll close this then :)

**Comment by Mogztter** [comment]
@ebousse I'm glad it's working for you, if you think it should be documented for future reference, please feel free to open a pull request :+1:
