### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by xrayn** [asciidoctor/asciidoctor-reveal.js#275]
Hi,

first of all, I would like to thank you very much for the great work that has been done here. 
Most of the very few problems I face while using asciidoctor-reveal.js I can get around quite well.
Most of them being CSS adjustments anyway.
Yet, I am wondering about the current development status of the project. For me, it seems it is currently stalled for whatever reason.

So please don't get this the wrong way, I am just asking and not complaining. :) Since I am not familiar with Ruby or sophisticated Javascript, I personally cannot really participate, I feel.

All the best ...

**Comment by obilodeau** [comment]
I've been busy on other things for a while but I'll review/merge PRs in the next few days and cut releases.

Bug triage or example documentation would be nice, do you think this is something you would be interested in helping with?

**Comment by xrayn** [comment]
That is great to hear, Sir!

Well, I'm open to help with documentation of examples or testing, if that helps. I could also provide some customized css that solves some issues I faced when using the software. I am just not sure where to put that kind of stuff. :)

**Comment by marcdexet-cnrs** [comment]
Hi,

I could help too, I'm using asciidoctor for courses, I'm around (I run a big grep around my folders) more than 3000 slides done with this fantastic tool.

**Comment by obilodeau** [comment]
I just released 2.0.1. If you could give it a test it would be appreciated!

Also, would you guys be interested in bug triage? Lastly, I built the `examples/` out of stuff I tried, it could be expanded. More in-depth examples could be done differently. I'm open to suggestions here.

**Comment by xrayn** [comment]
Version 2.0.1 works flawlessly for me. I did not have any issues. Regarding the bug triage? I am not familiar with that term. What do you mean with that?

**Comment by obilodeau** [comment]
> Version 2.0.1 works flawlessly for me. I did not have any issues. 

Awesome!

> Regarding the bug triage? I am not familiar with that term. What do you mean with that?

Quoting others: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Helping_the_DOM_team/Bug_Triage. However, our version would be a lot simpler but its basically going through issues labeling them. It could also be writing AsciiDoc that demonstrates issues with the least complexity. Writing examples that become test cases, etc.

**Comment by obilodeau** [comment]
I think this is resolved. Feel free to re-open if required.
