### ISSUE TITLE
Support reveal.js 3.8 and 3.9.1

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#296]
Note to self: There's probably not much to do here. But at least get the javascript requirements bumped and verify for new options.

**Comment by obilodeau** [comment]
I started working on this today. There are a few new options and plugins support will need to be verified since the API changed upstream but it looks like it is backward compatible.

**Comment by obilodeau** [comment]
After more work, the fact that upstream removed the `head.min.js` inclusion worries me. If we adopt reveal.js 3.8, the slides rendered by us will not be viewable by reveal.js 3.7.

The question becomes: is becoming incompatible with an older reveal.js release a break in API? For the javascript ecosystem, our `package.json` does specify the proper version although users are free to override. For the Ruby folks, if they followed the README they manage it by hand but with bundler our version should not bump for no reason.

If we consider stopping our support of 3.7 (and earlier) to be API breaking then we should do it during the 3.0 window. However, I don't expect many people to be forking their reveal.js so they should be reasonably able to upgrade. If so, it's not really an API break but more of a dependency update that is required. Then this would mean going smoothly by releasing 3.0.0 which works with 3.7 and then 3.1.0 which breaks 3.7 would be a better path forward for them.

My take: I think doing a 3.0.0 without reveal.js 3.8 (which works right now btw, just not the new features) and supporting it later for 3.1.0 would be reasonable but I would be interested in your thoughts @Mogztter, @mojavelinux, and others.

**Comment by mojavelinux** [comment]
I'm for a major version bump when reveal.js is upgraded, no matter what version we're coming from. Let's not cut corners when it comes to semver.

**Comment by Mogztter** [comment]
> If we adopt reveal.js 3.8, the slides rendered by us will not be viewable by reveal.js 3.7.

It sounds like a major version.

> I'm for a major version bump when reveal.js is upgraded, no matter what version we're coming from. Let's not cut corners when it comes to semver.

I agree 👍

**Comment by obilodeau** [comment]
I agree with you guys. Then I think I'm going to post-pone reveal.js 3.8 support to an asciidoctor-reveal.js 4.0.0 release (which I can do soon).

The reasoning is: I'm worried about the number of changes in this release and the number of additional changes required for reveal.js and their interaction with people's real slides. I would prefer to have a stable long-term base for reveal.js 3.0 until 3.7 with a proper stable API for asciidoctor.js and then offer users a version that works with reveal.js 3.8 cleanly built on top of all these new changes.

It is more releases but releasing is fairly cheap and it gets me to drink some more nice "release" beer :wink:

**Comment by Mogztter** [comment]
https://github.com/hakimel/reveal.js/releases/tag/3.9.1 is out! :smile:

**Comment by Mogztter** [comment]
@obilodeau Let me know if you need help as I need to implement https://github.com/asciidoctor/asciidoctor-reveal.js/issues/309 for a client :wink:

**Comment by obilodeau** [comment]
#301 is ready for review!

**Comment by obilodeau** [comment]
That's now in master.
