### ISSUE TITLE
backend document attribute not honored

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#306]
Tried to convert a document with `:backend: revealjs` today using the new Javascript CLI and it was rendered using the default html5 back-end.

Not sure if this is upstream or asciidoctor.js specific.

**Comment by Mogztter** [comment]
It might be a bug in Asciidoctor CLI.
I think the CLI should not force a default value: https://github.com/asciidoctor/asciidoctor-cli.js/blob/7055e675d429ad6b9b0b57bf395d383a0cc6b6a3/lib/options.js#L95

**Comment by obilodeau** [comment]
With the new explicit javascript CLI I feel like we can close this.

**Comment by Mogztter** [comment]
It's still an issue in Asciidoctor CLI, I will create an issue over there and fix it.
Nice catch :wink:
