### ISSUE TITLE
Allow to configure the total length of a presentation (in seconds) using totalTime

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#309]
https://github.com/hakimel/reveal.js/#speaker-notes-clock-and-timers

**Comment by Mogztter** [comment]
Nevermind it's not yet released: https://github.com/hakimel/reveal.js/commit/078ba6205066fcedeec59dbb6dd16d039558adb4
It's probably gonna be available in reveal.js 3.9.0.

**Comment by obilodeau** [comment]
The feature is in master now that #301 is merged.
