### ISSUE TITLE
Integer values of Reveal.js options are not set by template

### ISSUE THREAD

**Issue by ncomet** [asciidoctor/asciidoctor-reveal.js#312]
It seems integer values of options

- :revealjs_defaultTiming: 60
- :revealjs_autoSlide: 10

for instance, are not set properly by template. 
It works fine with boolean and textual values though.

**Comment by obilodeau** [comment]
I built a simple deck to reproduce your issue:

```
= Title Slide
:revealjsdir: reveal.js
:revealjs_defaultTiming: 60
:revealjs_autoSlide: 10000

== Slide One

* Foo
* Bar
* World

== Slide Two

Hello World

[NOTE.speaker]
--
Testing
--

== Slide Trois

Fancy
```

`:revealjs_autoSlide:` is in milliseconds (as documented) so 10 is blazingly fast. It does work on that slide deck. Using 10000 also works and is probably what you expected.

I can see that default timing is also set to 60 in the javascript but it is not visible in the speaker notes to me. I'm unsure why and maybe I'm not looking at the right place sine I never used that feature.

**Comment by obilodeau** [comment]
It looks like slides pacing (`defaultTiming` option) only works when there is a web server to serve the slides (there's probably some websocket action going on between the presenter and the speaker views). See screenshot (with same example deck):

![reveal js - Slide Notes - Google Chrome_004](https://user-images.githubusercontent.com/546325/72587621-be420f80-38c3-11ea-9065-a83cfb33879b.png)

Run a simple web server, load your slide deck through it, hit `s` and see if it works for you. I use `ruby -run -e httpd . -p 5000 -b 127.0.0.1` as documented in the README.

**Comment by ncomet** [comment]
Hi ! 
Thanks for the quick reply. I am indeed serving the slides from a server. I’ve noticed the timing does not work locally. 

I will try to find out what happens in my case. I am using the asciidoctor.js converter. Maybe the problem comes from here. 

(I am only interested by the defaultTiming option)

**Comment by obilodeau** [comment]
My tests were done with the JavaScript stack so it should not be the cause
of the issue. Using reveal.js 3.7.0.

If you look at the resulting HTML is the 60 value rendered properly and is
valid javascript?

**Comment by ncomet** [comment]
I tried :

:revealjs_defaultTiming: 40
or
:revealjs_defaulttiming: 40

No matter what the html output is : 

```
  // Specify the average time in seconds that you think you will spend
  // presenting each slide. This is used to show a pacing timer in the
  // speaker view
  defaultTiming: 120,
```

It is valid JS, but somehow the value is not picked up.

**Comment by obilodeau** [comment]
According to your repo, you are using a version with a bug: https://github.com/ncomet/oss-koson-2020/blob/master/package-lock.json#L71.

`npm update` your `package.json`.

See https://github.com/asciidoctor/asciidoctor-reveal.js/issues/263#issuecomment-500102771 for details.

[2.0.1](https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v2.0.1) fixes that problem. 

However, the latest version (and the one I tested) is [3.0.0](https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v3.0.0) but there is a font-awesome issue so 3.0.1 should be released soon.

**Comment by ncomet** [comment]
Thanks a lot, it was indeed a bug of 2.0.0. I close the issue.
