### ISSUE TITLE
deprecate the old npm package

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#314]
https://www.npmjs.com/package/asciidoctor-reveal.js/

We need to make sure that people know we changed names

**Comment by obilodeau** [comment]
I think I'm going to deprecate the package using the `npm deprecate` feature: https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

The message will say:
> This package has been renamed @asciidoctor/reveal.js. The package you are depending on, asciidoctor-reveal.js, will no longer receive any updates. Please update your package.json to use @asciidoctor/reveal.js.

Thoughts @Mogztter and @mojavelinux?

**Comment by Mogztter** [comment]
I think it's fine :+1:

**Comment by obilodeau** [comment]
Done
![adrjs-npm-old-deprecated](https://user-images.githubusercontent.com/546325/74804140-5c533c00-52ad-11ea-9511-236662063daa.png)
