### ISSUE TITLE
Some attributes can't be overriden from the command line

### ISSUE THREAD

**Issue by matklad** [asciidoctor/asciidoctor-reveal.js#321]
Hi!

I am using asciidoctor-revealjs to create a bunch of presentations from several source file. All the presentations share common revaljs attributes, so. instead of repeating them at the begining of each document, I've tried to move them to the command like, like this:

```bash
ATTRS="-a=customcss=slides.css -a=revealjs_width=1920 -a=revealjs_height=1080 -a=source-highlighter=highlightjs"

bundle exec asciidoctor-revealjs $ATTRS my-slides.adoc
```

I see that my customcss attribute is honored and the css is indeed loaded. Other attributes seem to be ignored though, and default values are used instead.

**Comment by obilodeau** [comment]
It's weird that one would work but the others wouldn't... I checked what the Bespoke and PDF converter do and it is the same as us.

The parsing of options does happen here: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/35b2bfadd34711c6b62d6f7e013b80b9b501d621/bin/asciidoctor-revealjs#L20

I'm not sure if this is a problem in upstream I will need to debug further. @mojavelinux thoughts?

**Comment by matklad** [comment]
Wait, `--attribute` works, but `-a` doesn't. I think that's the culprit here. Ie, when trying to bisect this I've accidently switched between `--attribute` and `-a` syntaxes without noticing it, and this is what seems to matter here.

**Comment by Mogztter** [comment]
I believe the syntax is invalid, it should be:

```
ATTRS="-a customcss=slides.css -a revealjs_width=1920 -a revealjs_height=1080 -a source-highlighter=highlightjs"

bundle exec asciidoctor-revealjs $ATTRS my-slides.adoc
```

(no equal sign after `-a`)

**Comment by matklad** [comment]
Yeah, it seems like it's just me being confused by the CLI, and not some bug, sorry for the noise :sweat_smile:

**Comment by Mogztter** [comment]
No worries :wink:
