### ISSUE TITLE
Bug? `title-slide-background-video` but only `background-opacity`

### ISSUE THREAD

**Issue by bentolor** [asciidoctor/asciidoctor-reveal.js#323]
See : 
https://github.com/asciidoctor/asciidoctor-reveal.js/blob/35b2bfadd34711c6b62d6f7e013b80b9b501d621/templates/document.html.slim#L86

All title slides attributes are in the form `title-slide-xxx` except opacity, which is only `background-opacity`. Is this by design or a bug?

**Comment by obilodeau** [comment]
Great catch!

**Comment by bentolor** [comment]
Yeah – I'm this strange guy _actually using_ these weird features nobody ever think they're needed. 

I'm must say I'm really quite impressed with the coverage of the rather esoteric revealjs features!

**Comment by bentolor** [comment]
Oh – it was me introducing this bug? What a shame! Sorry, @obilodeau

**Comment by obilodeau** [comment]
My latest deck for an internal presentation started using `background-opacity`. Haven't applied it to a title slide though. Using opacity is pretty neat, especially for video backgrounds. I was surprised by the quality of the royalty-free videos on Pixabay. I'll definitely do more of this.

I noticed that opacity hasn't been integrated into the background image new syntax though:

```AsciiDoc
== !

image::landscape.jpg[background, size=contain, opacity=0.7]
```

I'll try to add that eventually.

**Comment by bentolor** [comment]
I found https://www.pexels.com/ also to be an astonishing source of high-quality, no-fuss free video content.
