### ISSUE TITLE
how to text-align left on paragraph

### ISSUE THREAD

**Issue by bartoleo** [asciidoctor/asciidoctor-reveal.js#33]
I have not found a way to align left paragraphs.

I tried using a role, but the class name is injected inside a span.

**Comment by mojavelinux** [comment]
This is currently accomplished using the following AsciiDoc:

```
[.text-left]
Align me to the left.
```

and some docinfo content

```html
<style>
.text-left {
  text-align: left;
}
</style>
```

As I've mentioned in a few of the other issues, we're going to need to inject some common CSS into the output that support AsciiDoc content types and options, like the text-left role.

**Comment by bartoleo** [comment]
Thank you,
it worked

**Comment by Paimard** [comment]
i did it but all texts are in left side now. i will only the Tille in the left side

**Comment by refaelsh** [comment]
@ghost Can you please show us what you tried?
