### ISSUE TITLE
Host the examples on gh-pages/netlify?

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#336]
The _examples_ directory has a lot of good examples that can inspired people and help them get started.
I think it could be useful to host them on gh-pages or netlify.

The Asciidoctor Gradle Examples project is already doing that:
- https://github.com/asciidoctor/asciidoctor-gradle-examples
- http://asciidoctor.github.io/asciidoctor-gradle-examples/
- http://asciidoctor.github.io/asciidoctor-gradle-examples/asciidoc-to-revealjs-example/asciidocRevealJs/example-deck.html#/

**Comment by obilodeau** [comment]
Similar to #230

**Comment by Mogztter** [comment]
Ooops missed that one, sorry 😓

**Comment by Mogztter** [comment]
I've requested access to the repository from Netlify.
@obilodeau Not sure if you have the rights to accept this request or if only Dan can do it... could you please check?

**Comment by obilodeau** [comment]
I checked and, although I'm an admin of this repo, this seems to require organization access. It looks like @mojavelinux will have to do it.

**Comment by Mogztter** [comment]
We can now publish on Netlify: https://asciidoctor-revealjs-examples.netlify.com/
I think we should add a simple index page with links:

- Asciidoctor reveal.js 4.0.0
- Sample presentation
- ...

Do we want to publish a presentation per feature or a single presentation with the most common features? I don't think it's possible to include all features in one presentation without being boring 😅
