### ISSUE TITLE
Broken syntax highlighting on master with node

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#342]
When `lib/asciidoctor-revealjs/highlightjs.rb`'s `HIGHLIGHT_PLUGIN_SOURCE` is converted, there's a `\n` somewhere in that string that gets transformed into a newline in the destination HTML resulting in a broken line of javascript.

Error console:
![adrjs-node-js-newline](https://user-images.githubusercontent.com/546325/74702301-9a7e2c00-51d7-11ea-8d00-29440e31b72b.png)

Ruby code with the `\n`:
![adrjs-node-js-newline-ruby-ok](https://user-images.githubusercontent.com/546325/74702308-a0740d00-51d7-11ea-8c0a-21a969cbea22.png)

Converted to HTML with a newline (instead of the `\n`):
![adrjs-node-js-newline-html-not-ok](https://user-images.githubusercontent.com/546325/74702312-a4079400-51d7-11ea-862b-17d16d85cac7.png)

**Comment by obilodeau** [comment]
The javascript is in double-quote context and yet the newline is added without being escaped. Maybe it confuses Opal because it is wrapped in single quotes?

![adrjs-node-js-newline-javascript](https://user-images.githubusercontent.com/546325/74703302-c0f19680-51da-11ea-92e9-db8dffe68293.png)

Also, there are more problems later in the same source file:
![adrjs-node-js-newline-javascript-more](https://user-images.githubusercontent.com/546325/74703449-3493a380-51db-11ea-800d-5f17e224169c.png)

Looking for a solution or a workaround.

**Comment by obilodeau** [comment]
I tried splitting the long string and using a heredoc string instead of `%q{}` but it didn't work. I looked for open issues in the Opal repository and I didn't find anything.

@Mogztter, any idea?

**Comment by Mogztter** [comment]
The problem is that we are using `template.sub('//OPAL-GENERATED-CODE//', builder.to_s)` and `sub` is not doing a simple search and replace but somehow "unescape" `\`...
