### ISSUE TITLE
":revealjs_plugin_pdf: enabled" produces "Uncaught ReferenceError: require is not defined"

### ISSUE THREAD

**Issue by stenzengel** [asciidoctor/asciidoctor-reveal.js#344]
When `:revealjs_plugin_pdf: enabled` is added as described in the [readme](https://github.com/asciidoctor/asciidoctor-reveal.js/#default-plugins), the browser console (Chrome and Firefox) displays the following error:
```
Uncaught ReferenceError: require is not defined
    at print-pdf.js:13
```

I wonder if this plugin needs to be activated at all, because adding `?print-pdf` at the end of the URL seems to work correctly, even if this plugin is not activated.

**Comment by obilodeau** [comment]
What version of asciidoctor-reveal.js are you using? I think you are correct by stating that the plugin doesn't need to be activated. On master, I'm 100% sure but other versions I would need to look. I'll need to remove that part of the documentation.

**Comment by stenzengel** [comment]
I use:
```
"@asciidoctor/reveal.js": "^3.1.0",
"asciidoctor": "^2.1.1",
```

**Comment by obilodeau** [comment]
I managed to track this down. With reveal.js 3.7.0 (the one recommended with asciidoctor-reveal.js 3.1.0), the PDF plugin no longer exists, printing works without it.

Later today I'll modify the documentation:
* [ ] in a 3.1.x maintenance branch: say that the plugin is not required with reveal.js 3.7
* [ ] on master: remove all references to the PDF printing plugin

Thanks for the report!

**Comment by stenzengel** [comment]
Thanks!

The hint, that a PDF print is available via `?print-pdf` on chrome browser, was helpful for me.
