### ISSUE TITLE
Apply [.step] to something that is not a list

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-reveal.js#347]
I would like to reveal several sentences one-by-one.

There's a nice `[.step]` [feature](https://github.com/asciidoctor/asciidoctor-reveal.js/#fragments) that does exactly that. But I cannot figure out what should be the syntax if I want to apply it to something that is not a list.

The best thing I could invent is:

```adoc
= Title
:revealjsdir: https://cdn.jsdelivr.net/npm/reveal.js@3.9.2

== !

[.step]
--
One

Two
--

```

But this way, both sentences are immediately shown when you open the slide.

This also doesn't work:

```adoc
= Title
:revealjsdir: https://cdn.jsdelivr.net/npm/reveal.js@3.9.2

== !

--
[.step]
One

[.step]
Two
--
```

I'm not sure, but this issue could be a duplicate of #140

**Comment by slonopotamus** [comment]
Okay, it _is_ possible:

```adoc
= Title
:revealjsdir: https://cdn.jsdelivr.net/npm/reveal.js@3.9.2

== !

[.fragment]
--
Fragment one
--

[.fragment]
--
Fragment two
--
```

**Comment by Mogztter** [comment]
Do you want to document this feature here: https://github.com/asciidoctor/asciidoctor-reveal.js#fragments?
I think it would be simplified right?

```adoc
= Title
:revealjsdir: https://cdn.jsdelivr.net/npm/reveal.js@3.9.2

== !

[.fragment]
One

[.fragment]
Two
```

**Comment by slonopotamus** [comment]
Oh, I completely forgot about this issue. Yeah, I believe documentation needs to cover this topic.

**Comment by Mogztter** [comment]
Let's do that once the migration to Antora is completed.

**Comment by slonopotamus** [comment]
I am actually going to close this as a duplicate of #140.

**Comment by Mogztter** [comment]
Thanks, I wasn't aware of #140! :+1:
