### ISSUE TITLE
Cannot use MathJax locally, only via CDN

### ISSUE THREAD

**Issue by akosma** [asciidoctor/asciidoctor-reveal.js#348]
Currently there is no way to specify that the MathJax library should be loaded locally, instead of from a CDN. This would be akin to using the `:revealjsdir:` attribute that specifies a location for the library, for example within the `node_modules` folder.

In the source of `document.html.slim` there's a `cdn_base` variable [set](https://github.com/asciidoctor/asciidoctor-reveal.js/blob/8ad7fde2f23e0a36281a0b0d1721722b98e6f4ec/templates/document.html.slim#L15), which is [used](https://github.com/asciidoctor/asciidoctor-reveal.js/blob/8ad7fde2f23e0a36281a0b0d1721722b98e6f4ec/templates/document.html.slim#L55) for the URL to MathJax, and it cannot be overridden by an attribute right now.

A variable such as `:mathjaxdir:` or similar could specify the location of the library, either locally or in another server, instead of just a CDN.

**Comment by obilodeau** [comment]
### Example required

Can you provide a one-slide AsciiDoc document with MathJax in it, please? I realize we don't have anything in `examples/` and I wouldn't know what to write myself.

### DIY

Supporting that feature should be relatively straightforward, do not hesitate if you want to attempt it. `HACKING.adoc` has documentation on how to interact with templates when trying to implement something (pry byebug REPL).

### reveal.js support

Lastly, reveal.js also [has MathJax support](https://github.com/hakimel/reveal.js#mathjax) on its own.  It looks like you can specify a path to `MathJax.js` in a configuration block. You can try it with reveal.js by using our custom plugin and plugin customization features.

**Comment by akosma** [comment]
Please find attached a simple possible project to demonstrate the issue: [issue348.zip](https://github.com/asciidoctor/asciidoctor-reveal.js/files/4249105/issue348.zip). You can use the `make` command to rebuild the `slides.html` if needed.

Observations:

1. The only way that I found to embed equations is by using the `:stem:` attribute, which automatically embeds a `<script>` tag pointing to the CDN version of MathJax. There is no way 
2. The `:revealjs_plugin_math: enabled` attribute is ignored, yet the documentation suggests that this should be the way to enable the official `math` Reveal.js plugin
3. Same for the configuration of the plugin, using `:revealjs_math_mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js'` (this is something I came up with, wasn't actually expecting it to work, but follows naming conventions for other settings)

Thanks for your help! Let me know if I can provide more information.

**Comment by akosma** [comment]
I just realized this might be an Asciidoctor issue? Just found this one:
https://github.com/asciidoctor/asciidoctor/issues/761

**Comment by akosma** [comment]
@obilodeau any comments about the PR? Thanks!

**Comment by obilodeau** [comment]
Sorry, I was away on vacation with little computer time. I'm going to take a look at it later tonight.

Thanks!

**Comment by obilodeau** [comment]
@akosma, right now the example you provided in #350 doesn't use the `:mathjaxdir:` attribute and everything seems to work. Can you add a `examples/mathjax-cdn.adoc` example that demonstrate the use of that feature and uses markup that requires a more recent version?

Basically I would like this new example to:
* comment out the `mathjaxdir` attribute, see that the converted slides are broken
* re-enable the attribute and see the slides being correct

**Comment by obilodeau** [comment]
Also, please voice your opinion on #355. Thanks!

**Comment by akosma** [comment]
> @akosma, right now the example you provided in #350 doesn't use the `:mathjaxdir:` attribute and everything seems to work. Can you add a `examples/mathjax-cdn.adoc` example that demonstrate the use of that feature and uses markup that requires a more recent version?
> 
> Basically I would like this new example to:
> 
>     * comment out the `mathjaxdir` attribute, see that the converted slides are broken
> 
>     * re-enable the attribute and see the slides being correct

Just created a new PR: https://github.com/asciidoctor/asciidoctor-reveal.js/pull/359
