### ISSUE TITLE
.columns.wrap with images doesn't wrap

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#353]
Test case. To be dropped in `examples/` and images will resolve properly.

```asciidoc
= Grid Wrapping Tests
:imagesdir: images/
// reveal.js config
:revealjs_hash: true
:revealjs_center: false
:revealjs_height: 1080
:revealjs_width: 1920

[.columns.wrap]
== Should Wrap But Doesn't

[.column]
* Things here should wrap
* But instead images shrink

[.column]
image::cover.jpg[width=900px]

[.column]
image::70s.jpg[width=900px]
```

This looks like this:
![adrjs-grid-wrap-issue](https://user-images.githubusercontent.com/546325/76717636-911aad80-670a-11ea-927b-ffd58e372e23.png)

If I disable `flex-basis` on `.columns .slide-content > .column` it becomes:

![adrjs-grid-wrap-issue-ok](https://user-images.githubusercontent.com/546325/76717691-befff200-670a-11ea-8107-9bc62fc15925.png)

Which would be more what I would expect.

However, I wonder if that is a viable fix. @Mogztter any ideas?

**Comment by Mogztter** [comment]
Damn! And now I don't specifically remind why `flex-basis` was important but I'm pretty sure that if you remove it, it will have some side effects.

To limit impact, we could override it when `wrap` is enabled:

```css
.columns.wrap .slide-content > .column {
  flex-basis: auto;
}
```

I believe `auto` is the default value: https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis
