### ISSUE TITLE
Should we bump to latest MathJax 2.7.x?

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#355]
Request for comments

MathJax 2.4 is about to be 6 years old. The latest stable release 2.7.5 is 2 years old. It seems pretty stable. Trying the example that @akosma provided with it worked.

Release notes of in-between versions don't reveal any backward-incompatible changes:
* https://www.mathjax.org/mathjax-v2-5-now-available/
* https://www.mathjax.org/mathjax-v2-6-now-available/
* https://www.mathjax.org/mathjax-v2-7-now-available/
* Several 2.7.x point releases with the latest being: https://www.mathjax.org/mathjax-v2-7-5-now-available/

I think we should update our default version to 2.7.5 given that it seems backward-compatible, any objections?

**Comment by akosma** [comment]
I think it's a good idea to update.

**Comment by Mogztter** [comment]
I cannot attest that 2.7.5 is 100% backward compatible but I think we should upgrade.
We should even consider upgrading to MathJax 3 but that's another subject :wink:

**Comment by obilodeau** [comment]
So, since the associated PR was posted, MathJax is at 2.7.8. However, in the meantime they released MathJax 3. I'm not willing to move to MathJax 3 especially now that revealjs introduced v4 which means that we are heading towards a major release to support it anyway which would be a perfect time to move MathJax to v3.

However, thinking about stability, [cloudflare doesn't host MathJax 2.7.8](https://www.mathjax.org/MathJax-v2-7-8-available/) and since `cdn_base` is used to resolve several CSS and JS dependencies, I don't want to break it apart now. I'm going to reluctantly merge a mathjax 2.7.6 support and open a ticket on a move to v3 along with reveal.js 4.
