### ISSUE TITLE
Question: Use icons in slide title

### ISSUE THREAD

**Issue by mrcasablr** [asciidoctor/asciidoctor-reveal.js#362]
I'm loving asciidoctor-revealjs to build nice slides and it's getting better and better with every release.

I was wondering if there is a way to use font-awesome fonts in slide title?

**Comment by obilodeau** [comment]
Good question. I never tried. Can post an example AsciiDoc of what you've tried?

**Comment by obilodeau** [comment]
Yes, you can. I wasn't sure, so I added an example in `examples/font-awesome.adoc` (added in 148bd5e).

Thanks for the idea! I usually used empty titles and then a font-awesome content instead but I never thought of using it directly in titles.
