### ISSUE TITLE
Upgrade font-awesome to 5.13.0

### ISSUE THREAD

**Issue by mrcasablr** [asciidoctor/asciidoctor-reveal.js#363]
I'm sure some of us could use the covid-19 fonts from 5.13.0 

https://fontawesome.com/changelog/latest

**Comment by obilodeau** [comment]
Great idea. I wasn't aware of them.

If you are in a rush, you can either [patch this plugin](https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/document.html.slim#L34) or [negate the `iconfont-remote` attribute](https://github.com/asciidoctor/asciidoctor.org/issues/361). However, I've never tried that last option personally, from my casual reading of the code, it should work.

In any case, I'm scheduling an update but I'm not working on asciidoctor-reveal.js right now. Other time-sensitive volunteer activities going on.

**Comment by Mogztter** [comment]
Contributions are welcome, feel free to submit a pull request to update the version in `templates/document.html.slim` as mentioned by Olivier.
