### ISSUE TITLE
broken upstream documentation links

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#371]
Introduced by revealjs 4.0 release tracked by #370 

For master, we need to update links to https://github.com/hakimel/reveal.js/blob/v3.9/README.md instead of https://github.com/hakimel/reveal.js/blob/master/README.md.

Should update master (which will become latest 4.x) and the 3.x maintenance branch as well.

**Comment by rquinio** [comment]
These broken links are very annoying ! I've opened a PR to fix it.
