### ISSUE TITLE
Grid layout: 3 columns with 1/3 each do not seem to fit in a single row

### ISSUE THREAD

**Issue by 0x1af** [asciidoctor/asciidoctor-reveal.js#372]
**Background:**
I was trying to create a 3x2 grid layout with images (plus captions and where each image is revealed step-by-step)

**Code:**
```
:revealjs_transition: none
:icons: font
:revealjs_theme: white
:revealjs_slideNumber: true
:revealjs_center: false
//:customcss: customcss.css
:revealjs_width: 1680
:revealjs_height: 1050
:revealjs_hash: true

[.columns.wrap]
== Different Colors 

[.column.is-one-third]
[.fragment]
--
.Blue
image::https://upload.wikimedia.org/wikipedia/commons/f/ff/Solid_blue.svg[width=40%]
--
[.column.is-one-third]
[.fragment]
--
.Solid green but with longer caption
image::https://upload.wikimedia.org/wikipedia/commons/2/29/Solid_green.svg[width=40%]
--
[.column.is-one-third]
[.fragment]
--
.Solid red
image::https://upload.wikimedia.org/wikipedia/commons/2/25/Red.svg[width=40%]
--
[.column.is-one-third]
[.fragment]
--
.Solid blue
image::https://upload.wikimedia.org/wikipedia/commons/f/ff/Solid_blue.svg[width=40%]
--
[.column.is-one-third]
[.fragment]
--
.Blue
image::https://upload.wikimedia.org/wikipedia/commons/f/ff/Solid_blue.svg[width=40%]
--
[.column.is-one-third]
[.fragment]
--
.Solid green but with longer caption
image::https://upload.wikimedia.org/wikipedia/commons/2/29/Solid_green.svg[width=40%]
--
```
**Result:**
![result_with_33 3width](https://user-images.githubusercontent.com/34983480/83269927-10773380-a1c8-11ea-87ef-6874d691f81a.png)
Not what I was hoping for :blush:  . I was hoping three columns with one third each would make a single row.

By adjusting  the width from 33.3333% to 31.9% in the css things start  looking as I would have wished:
```
columns .slide-content > .column.is-one-third {
    flex: none;
    width: 31.9%;
}
```

![result_with_31 9width](https://user-images.githubusercontent.com/34983480/83269926-0f460680-a1c8-11ea-9c2c-9206f8a72914.png)

I am not yet sure whether this is a bug, or just me. 

Could one of you give a try please?

Thanks in advance!

**Comment by obilodeau** [comment]
You have wrap and many one-thirds. I don't think it is how this is intended to work. Wrapping is like saying "put as much as you can then create a new row". Whereas one-third is "take one-third of the screen's real estate".

Naively, I would have used one-third and put figure 1 and 4 in the same block. Or, I would have used wrapping alone.

That said, you provided AsciiDoc source and screenshots. This is the perfect bug report. I'll try the suggestions I mentioned, try validating image sizing and if both of these don't fix your issue, we should consider changing the CSS.

**Comment by 0x1af** [comment]
@obilodeau - Thank you for the kind reply.
I started inspecting the html with chromium. There is a padding defined  in the asciidoctor-compatibility.css.
https://github.com/asciidoctor/asciidoctor-reveal.js/blob/505cea0eaf044cc96d810ac16a5fde694432f55e/templates/asciidoctor-compatibility.css#L90
By respecting the 0.75rem for the overall width of each column I managed to get 3 items in a row.
I added the following as a custom css:

```
.columns .slide-content > .column {
    --padding-value: 0.75rem;
    padding: var(--padding-value) !important;
}

div.column {
    width: calc(33.3333% - 2* var(--padding-value, 0)) !important;
}
```
Please note, I only know very little about css, so I am not sure if this is good solution.

**Comment by Mogztter** [comment]
Hey @0x1af !

In this case it would probably be better to use a `display: grid` layout but you are right the padding skew the 1/3 ratio.

I moved the padding on the content inside the column, it should fix this issue.
