### ISSUE TITLE
Custom alignment of text blocks

### ISSUE THREAD

**Issue by fedochet** [asciidoctor/asciidoctor-reveal.js#380]
Hi! Is there a built-in way to adjust the alignment of the text on the slides? 

For example, if I want to make my slides title right or left aligned instead of center-aligned, how can I do that? I would like to do that without directly editing `.css`, if possible

**Comment by Mogztter** [comment]
Since Asciidoctor supports text alignement out-of-the-box on sections and paragraphs it seems reasonable.
