### ISSUE TITLE
use a custom css with disableLayout option of revealjs

### ISSUE THREAD

**Issue by g4gilson** [asciidoctor/asciidoctor-reveal.js#381]
Hi, I'm trying to set the disableLayout option to true but the option seems to be not supported or don't work with the syntax:
```
:revealjs_disableLayout: true
```

in .adoc files.
I wonder how can I use this option with asciidoctor-reveal.js or have a similar behaviour with another trick and why this option seems to be deliberated avoid

**Comment by g4gilson** [comment]
Add option:
:backend: revealjs
is necessary to take into account the ":revealjs_disableLayout: true" option.

**Comment by g4gilson** [comment]
Was working by using compiled asciidoctor reveal js on my computer. Issue still open

**Comment by Mogztter** [comment]
This option is currently not supported by the converter.
If you want to contribute this feature, you will need to add it in `templates/document.html.slim`.


You can take inspiration from `revealjs_help`:

https://github.com/asciidoctor/asciidoctor-reveal.js/blob/52e9335f630e128b7ae7c88164f770ee69507b19/templates/document.html.slim#L151



For reference, here's the reveal.js default configuration: https://github.com/hakimel/reveal.js/blob/94d98ff7d89e35c7d5b289ba387cdb0d42b30793/js/reveal.js#L115-L117

And here's what you would need to add in the `document.html.slim` file:

```slim
  disableLayout: #{to_boolean(attr 'revealjs_disablelayout', false)}, 
```

**Comment by Mogztter** [comment]
@g4gilson I plan to include this enhancement/fix as part of the next release. Do you want to contribute it or should I go forward and take care of it?

**Comment by g4gilson** [comment]
If that don't bother you, you can take care of it. I had some difficulties to make the building environment and your previous answer is what I was thinking to add it :+1: . Thank you for your answer :)

**Comment by Mogztter** [comment]
No worries, thanks for reporting this issue :+1:
