### ISSUE TITLE
Question: Recommended up-to-date pathway to publish asciidoctor-reveal.js slides to gh-pages

### ISSUE THREAD

**Issue by dquesadacr** [asciidoctor/asciidoctor-reveal.js#382]
I would like to know if there is a recommended, up-to-date, way to publish slides generated with asciidoctor-reveal.js to github pages. I have read several possible methods e.g. using Gulp, Grunt, Travis, etc, most of them are older than 3 years. After trying several methods and combinations I haven't been able to render the slides properly, instead I get a half formatted html file where all the slides are concatenated (https://dquesadacr.github.io/cdo_climate_modelling/, repo: https://github.com/dquesadacr/cdo_climate_modelling), in contrast to how they look when I open the html file in my browser.

Due to my background, I am not that familiar with some of the tools used here, but I would gladly learn. Any tip would be greatly appreciated!

**Comment by Mogztter** [comment]
Hey @dquesadacr 

The slides now look fine at https://dquesadacr.github.io/cdo_climate_modelling right? I guess that you found a solution?
Are you willing to share what you did?

**Comment by ggrossetie** [comment]
Closing but feel free to submit a pull request to document what/how you did.
