### ISSUE TITLE
Migrate the build from Travis CI to GitHub Actions 

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#384]
Travis CI is no longer friendly to Open Source, let's move to GitHub Actions.

**Comment by jirutka** [comment]
By “no longer friendly to Open Source” you mean not sponsoring OSS projects by providing their resources for free without limits anymore? I understand and agree with moving to GitHub Actions, but saying that in this way is quite disrespectful to Travis.

**Comment by Mogztter** [comment]
> but saying that in this way is quite disrespectful to Travis.

I didn't mean it that way.
My understanding is that they broke their commitment to Open Source. I'm grateful that they did provide a great service for many years to Open Source projects but that's no longer the case.
I know that some community members have experienced builds taking literally hours or even days.

**Comment by mojavelinux** [comment]
I second the way that Guillaume framed it. I'll also add that they did it
in an insidious and incredibly immature way, especially knowing how much of
an integral part they had become to OSS on GitHub. They a) didn't
communicate at all with us personally about this change, deciding only to
mention it in passing on their blog and b) started throttling jobs for OSS
by hours knowning that it would hurt us. Personally, I'm not willing to
forgive this behavior. It's these actions, and their willingness to do
that, which makes me label them as not friendly to OSS. They rescinded
their commitment to OSS. If they didn't want to provide those resources,
then they shouldn't have made it in the first place. You are entitled to
your opinion. I have mine.

**Comment by Mogztter** [comment]
I will create a follow-up issue/pull request to add Windows in the CI as it requires additional extra care.
