### ISSUE TITLE
local MathJax doesn't seems to work with v4.0.1

### ISSUE THREAD

**Issue by g4gilson** [asciidoctor/asciidoctor-reveal.js#403]
MathJax path shall be set to online or local directory through:
```
:stem:
:revealjsdir: https://cdn.jsdelivr.net/npm/reveal.js@3.9.2
:mathjaxdir: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/
```
See: https://github.com/asciidoctor/asciidoctor-reveal.js/issues/348

After conversion and html inspection I have:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.4.0/MathJax.js?config=TeX-MML-AM_HTMLorMML"></script>
```
I have 2.4.0 instead of 2.7.0.
Path doesn't change when I try to use local path:
```
:mathjaxdir: my/local/path
```

**Comment by Mogztter** [comment]
Hey @g4gilson!

This feature is not yet released.
It was resolved in https://github.com/asciidoctor/asciidoctor-reveal.js/commit/b0568cc6eda3dec05b34cd29d90c62b095140f7e which is only available on the master branch from now.
It will be part of the upcoming 4.1.0 release.

**Comment by g4gilson** [comment]
Hi @Mogztter 

Sorry, didn't think about that because the issue was closed XD.
Will check that for future question.

**Comment by Mogztter** [comment]
No worries, hopefully 4.1.0 will be out soon :wink:

**Comment by Mogztter** [comment]
@g4gilson Version 4.1.0 is out! https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v4.1.0
