### ISSUE TITLE
Contributing dead link

### ISSUE THREAD

**Issue by g4gilson** [asciidoctor/asciidoctor-reveal.js#409]
In README, contibuting link:
Interested in contributing? We are interested! Developer-focused documentation is ***over here***.
is dead.
Maybe replace:
https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/HACKING.adoc
to
https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/docs/modules/project/pages/hacking.adoc

**Comment by Mogztter** [comment]
Good catch!
Please feel free to submit a pull request fix it (otherwise I will later today).
