### ISSUE TITLE
/?print-pdf with pdf plugin does not include images

### ISSUE THREAD

**Issue by a4z** [asciidoctor/asciidoctor-reveal.js#413]
I just wanted to export a presentation to pdf, but it misses all the pictures.

The presentation works well with the pictures.

I think I used it already, pdf generation with images, and it worked, so I wonder what problem I have now? 
Is there anything special I have to care about?

**Comment by Mogztter** [comment]
Just tried on https://asciidoctor-revealjs-examples.netlify.app/release-4.1.html?print-pdf#/ and it seems to be working just fine. You can see cat pictures on slide 8, 9 and 10 (progressively revealed).

Any error in the console (Developer Tools)? Could you please provide a reproduction case?

**Comment by a4z** [comment]
wow, what an interesting mistake I was able to make

Slides, but no pictures:
`http://localhost:9090/my/talk/index.html/?print-pdf`

Slides with picture:
`http://localhost:9090/my/talk/index.html?print-pdf`

Thanks for the feedback! 
It finally helped me to spot the disturbing `/` and make everything work


(PS, the error history)
just appending `?print-pdf` to the talk url, what is `http://localhost:9090/my/talk/index.html#/`
