### ISSUE TITLE
Issue with speaker notes when generating with cdn reveal.js

### ISSUE THREAD

**Issue by ttych** [asciidoctor/asciidoctor-reveal.js#414]
With the following presentation, https://docs.asciidoctor.org/reveal.js-converter/latest/converter/features/#basic-presentation-with-speaker-notes

I try the following asciidoctor command 
```
 bundle exec asciidoctor-revealjs \
  -a revealjsdir=https://cdn.jsdelivr.net/npm/reveal.js@3.9.2 CONTENT_FILE.adoc
```
as described here : https://docs.asciidoctor.org/reveal.js-converter/latest/setup/ruby-setup/#rendering-the-asciidoc-into-slides

Slides generation is successful, but when pressing `s` instead of loading the speaker notes, it renders the raw html from the cdn URL.

It looks like a security feature to avoid loading external code ?
Is there anything special to configure, to have it functionnal ?

Example available here : https://ttych.github.io/test/presentation.html

Thanks for your help !

**Comment by mojavelinux** [comment]
jsDeliver states that "serving HTML pages is not supported for security reasons". So you'd have to use a different CDN or publish through a hosting platform such as GitHub Pages, GitLab Pages, Netlify, etc.

**Comment by ttych** [comment]
Many thanks for the clarification !

**Comment by Mogztter** [comment]
I believe that this answers your question so I'm closing this issue (feel free to reopen if that's not the case) :wink:
