### ISSUE TITLE
Use Docinfo to declare and configure plugins

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#418]
Currently, we are using a text fragment to declare additional plugins. 
Here's an example:

```
{ src: 'revealjs-plugins/menu/plugin.js' },
{ src: 'revealjs-plugins/chalkboard/plugin.js' }
```

As you can see the above text is not a valid JSON or JavaScript object. The text value will be used to replace a placeholder in our template.

(pseudo-code)
```hbs
<script>
  Reveal.initialize({
    // ...
    dependencies: [
      {{ pluginsDefinition }}
    ]
  });
</script>
```

When generating a presentation, we will replace `{{ pluginsDefinition }}` with the text value:

```html
<script>
  Reveal.initialize({
    // ...
    dependencies: [
      { src: 'revealjs-plugins/menu/plugin.js' },
      { src: 'revealjs-plugins/chalkboard/plugin.js' }
    ]
  });
</script>
```

We are using a similar technique to configure plugins.
Here's an example:

```
menu: {
  side: 'right'
},
keyboard: {
  67: function() { RevealChalkboard.toggleNotesCanvas() }, // toggle notes canvas when 'c' is pressed
  66: function() { RevealChalkboard.toggleChalkboard() },
  46: function() { RevealChalkboard.clear() },
  8: function() { RevealChalkboard.reset() },
  68: function() { RevealChalkboard.download() },
},
```

(pseudo-code)
```hbs
<script>
  Reveal.initialize({
    // ...
    {{ pluginsConfiguration }}
    // ...
  });
</script>
```

Using text fragments is error-prone because we cannot use any code assistance features. For instance, if I forgot to add a trailing comma, I will break the `Reveal.initialize` function because the code will be invalid.

It also duplicates some logic since Asciidoctor already provides a mechanism to add custom content (and safely read files).

I think we should introduce Docinfo after and before the `Reveal.initialize` function:

- `docinfo-preinit-revealjs.html`
- `docinfo-postinit-revealjs.html`

Here's the same example as before using the a pre-init Docinfo:

*docinfo-preinit-revealjs.html*

```html
<script>
globalThis.RevealConfig = {
  dependencies: [
    { src: 'revealjs-plugins/menu/plugin.js' },
    { src: 'revealjs-plugins/chalkboard/plugin.js' }
  ],
  menu: {
    side: 'right'
  },
  keyboard: {
    67: function() { RevealChalkboard.toggleNotesCanvas() }, // toggle notes canvas when 'c' is pressed
    66: function() { RevealChalkboard.toggleChalkboard() },
    46: function() { RevealChalkboard.clear() },
    8: function() { RevealChalkboard.reset() },
    68: function() { RevealChalkboard.download() },
  }
}
</script>
```

Then, we could use `globalThis.RevealConfig` to initialize reveal.js:

```html
<script>
  const builtinConfig = {
    // ...
  }
  const customConfig = globalThis.RevealConfig || {}
  Reveal.initialize(Object.assign(builtinConfig, customConfig))
</script>
```

The post-init could be use to configure reveal.js.

Here's an example using the new API (introduced in reveal.js 4) to register plugin:

```js
<script src="plugin/zoom/zoom.js"></script>
<script>
  Reveal.registerPlugin(RevealZoom)
</script>
```

We can also use the `addKeyBinding` API to add additional features:

```js
<script>
  Reveal.addKeyBinding({ keyCode: 84, key: 'T', description: 'Start timer' }, () => {
    // start timer
  })

  // The binding parameter can also be a direct keycode without providing the help description
  Reveal.addKeyBinding(82, () => {
    // reset timer
  })
</script>
```

The attribute `revealjs_plugins` and `revealjs_plugins_configuration` will be removed.

**Comment by g4gilson** [comment]
That seems to be more readable too. I haven't learnt JavaScript so I can't really understand but why splitting reveal.js initialize and post init?

It's not the same than:
``` javascript
<script src="plugin/zoom/zoom.js"></script>
<script>
  const builtinConfig = {
    // ...
  }
  const customConfig = globalThis.RevealConfig || {}
  Reveal.initialize(Object.assign(builtinConfig, customConfig))
  Reveal.registerPlugin(RevealZoom)
</script>
```

**Comment by Mogztter** [comment]
@g4gilson Thanks for your feeedback!
I was suggesting pre and post initialization because the converter automatically initialize reveal.js depending on some AsciiDoc attributes:

(pseudo-code)
```js
const controls = node.getAttribute('revealjs_controls', true)
const controlsTutorial = node.getAttribute('revealjs_controlstutorial', true)
const controlsLayout = node.getAttribute('revealjs_controlslayout', 'bottom-right')
Reveal.initialize({
  controls,
  controlsTutorial,
  controlsLayout,
  // ...
}
```

BUT I just learn that we can use `Reveal.configure` to update the initial configuration. So "pre-init" is not needed anymore.
We can do the following in "post-init":


```js
<script src="plugin/zoom/zoom.js"></script>
<script>
  const customConfig = {}
  Reveal.configure(customConfig)
  Reveal.registerPlugin(RevealZoom)
</script>
```

**Comment by g4gilson** [comment]
I think that have only one docinfo is better for maintenance too :+1:
