### ISSUE TITLE
Favicon is not included in HTML

### ISSUE THREAD

**Issue by bbenno** [asciidoctor/asciidoctor-reveal.js#419]
## Expected
Using the document attribute [`:favicon:`](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/favicon/) results in adding
```html
<link rel="icon" type="image/x-icon" href="favicon.ico">
```
to HTML header as in [Asciidoctor](https://github.com/asciidoctor/asciidoctor) using HTML backend.

## Actual
No such HTML element is inserted.

**Comment by Mogztter** [comment]
Hey @bbenno!
That would be a great addition, do you want to submit a pull request? You can take a look at the original implementation in Asciidoctor:

https://github.com/asciidoctor/asciidoctor/blob/3c7d2e8255d2f75dede0aab42ca32948ca4360e4/lib/asciidoctor/converter/html5.rb#L113-L123

You can add the logic just after this line: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/7bbad8d4b7e21c5beb8bce17eb12532d30c49e62/templates/document.html.slim#L18

We are using [Slim templates](http://slim-lang.com/). Let me know if you need help to get started.

**Comment by bbenno** [comment]
Hey @Mogztter, thx for the quick reply an the references.
Please have a look at the PR.
