### ISSUE TITLE
Vertical table alignment not working with reveal.js backend

### ISSUE THREAD

**Issue by Zlika** [asciidoctor/asciidoctor-reveal.js#42]
Hi !
The following code is working with the html5 backend, it prints a table with an image and a text, both vertically aligned. However, with the reveal.js backend, the vertical alignment is not honored.

[cols=".^1,.^2"]
|====================
| image:https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/2000px-Tux.svg.png[width=150] | I Love Linux
|====================

**Comment by mojavelinux** [comment]
The necessary styles are missing. You'd need to copy them into your theme CSS for now.

Here are the styles you need:

https://github.com/asciidoctor/asciidoctor/blob/master/data/stylesheets/asciidoctor-default.css#L235-L257

This is part of a larger issue that AsciiDoc requires CSS to activate certain features, so we need to include "base CSS" that works with all themes that implements the AsciiDoc-related features such as table alignment. HTML can only describe so much. CSS is needed for some of it.

**Comment by mojavelinux** [comment]
Related to #23.

**Comment by Zlika** [comment]
Thanks for the workaround!

**Comment by obilodeau** [comment]
This is fixed with #288. It will be part of the upcoming 3.0.0 release.
