### ISSUE TITLE
Drop or add better support for the Markdown plugin

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#432]
In theory, we support the Markdown plugin and we can enable it using `:revealjs_plugin_markdown: enabled` but in practice it's not as easy since we need to generate the following HTML structure (according to the reveal.js documentation):

```html
<section data-markdown>
  <textarea data-template>
    ## Slide 1
    A paragraph with some text and a [link](http://hakim.se).
    ---
    ## Slide 2
    ---
    ## Slide 3
  </textarea>
</section>
```

The problem is that the default converter does not allow to set the `data-markdown` HTML attribute on a `<section>` element and there's no AsciiDoc syntax to generate a `<textarea>`.

In other words, the only way to use this plugin is to declare the whole content using a passthrough:

```
= Presentation using Markdown plugin
:revealjs_plugin_markdown: enabled

++++
<section data-markdown>
<textarea data-template>
## Slide 1
A paragraph with some text and a [link](http://hakim.se).
---
## Slide 2
---
## Slide 3
</textarea>
</section>
++++
```

As you can see this is far from ideal... a potential solution would be to support Markdown at slide level using a literal with a `%markdown` option:

```
= Presentation using Markdown plugin
:revealjs_plugin_markdown: enabled

== Slide 1

[%markdown]
....
A paragraph with some text and a [link](http://hakim.se).
....

== Slide 2

== Slide 3
```

To be honest, I don't really see any benefit since we can already use a lightweight markup language... In my opinion we should drop support as I'm pretty sure nobody is using it (since it's not practical).

We could consider adding this feature again if someone makes a strong case.

**Comment by edl7878** [comment]
I think to keep the `:revealjs_plugin_markdown:` is good. It's possible to use markdown but it's not best practice in this case.

`[%markdown]` solution is ideal, but I agree with you to realize it is going further from the actual need.

**Comment by mojavelinux** [comment]
I'm with @Mogztter on this one. It's important to focus on what the goal of this tool is, and that's AsciiDoc.
