### ISSUE TITLE
Add support for built-in search plugin

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-reveal.js#433]
reveal.js 4.x (and 3.9.2) includes a built-in search plugin. By pressing `<ctrl>` + `<shift>` + `<f>` you can search slide content.

I think we should add an attribute to enable/disable this plugin:

```
:revealjs_plugin_search: enable
```

Since this plugin was not supported until now I think it should be disabled by default (i.e., this plugin should be explicitly enabled).

**Comment by edl7878** [comment]
Have been realized in resolves #370 add support for reveal.js 4.1.
