### ISSUE TITLE
Videos missing protocol

### ISSUE THREAD

**Issue by gtoast** [asciidoctor/asciidoctor-reveal.js#44]
When trying to embed a video in a slideshow, the video doesn't show up at all because its missing the "http:".  From my asciidoc:

```
video::70589461[vimeo]
````

From the exported reveal slideshow

```
<div class="videoblock"><div class="content"><iframe src="//player.vimeo.com/video/70589461" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div></div>
```

Looking at the block_video.html.slim reveals:
```
    - when 'vimeo'
      - start_anchor = (attr? :start) ? "#at=#{attr :start}" : nil
      - delimiter = '?'
      - autoplay_param = (option? 'autoplay') ? "#{delimiter}autoplay=1" : nil
      - delimiter = '&amp;' if autoplay_param
      - loop_param = (option? 'loop') ? "#{delimiter}loop=1" : nil
      - src = %(//player.vimeo.com/video/#{attr :target}#{start_anchor}#{autoplay_param}#{loop_param})
      iframe width=(attr :width) height=(attr :height) src=src frameborder=0 webkitAllowFullScreen=true mozallowfullscreen=true allowFullScreen=true
```

The YouTube block is similarly missing its protocol. Forgive me, if this is not broken and I'm missing something simple here...

**Comment by mojavelinux** [comment]
The long story short is that this was once required by Vimeo and YouTube (yes, using the empty protocol), but that restriction has since been lived and we can return to using a real protocol.

See the related issue in core: https://github.com/asciidoctor/asciidoctor/issues/1320

**Comment by gtoast** [comment]
Cool. I mightt try my hand at submitting a fix.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
For reference, see the latest code in core. https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L915-L973

**Comment by obilodeau** [comment]
Tested a vimeo video with current version. It works. This is fixed.
