### ISSUE TITLE
Partial code highlighting

### ISSUE THREAD

**Issue by rahulsom** [asciidoctor/asciidoctor-reveal.js#46]
Is it possible to do something like what this slide deck does - https://speakerdeck.com/pardom/kotlin-new-hope-in-a-java-6-wasteland/ on slide 31?

**Comment by mojavelinux** [comment]
io-slides-2012 has something similar. See http://io-2012-slides.googlecode.com/git/template.html#6

Achieving it will likely require a plugin for reveal plus some additional markup added by the converter.

**Comment by obilodeau** [comment]
@rahulsom should we close this or convert it into a feature request?

**Comment by rahulsom** [comment]
@obilodeau Sounds good.

**Comment by obilodeau** [comment]
Closing an old issue without much context that I didn't see before filing. See #225 to track this now.
