### ISSUE TITLE
Heading levels influencing revealjs behavior

### ISSUE THREAD

**Issue by jhkuperus** [asciidoctor/asciidoctor-reveal.js#473]
Yesterday I was tinkering with a series of slide decks that we convert to revealjs presentations using Asciidoctor-revealjs. We noticed some strange behaviour with `include` and source highlighting would not work at all. After some digging, I found the problem to be in how we structured headings in the document.

TL;DR: There seem to be assumptions about root-level headings (with just 1 `=`) that influence whether certain features are correctly turned on. The main question is: is this a bug or is it something that we should document as a caveat/troubleshooting thing?

I'll detail the exact cause and fix of the issue here.

### Syntax Highlighting

Our document is structured with a single `index.adoc`, which includes a series of topics to combine into a single document. These documents looked like this:

`index.adoc`:
```asciidoc
== Presentation Title
:doctype: book
:imagesdir: ../../../images/moduleX
:source-highlighter: highlight.js

include::01-intro.adoc[]

include::02-encapsulation.adoc[]
```

`01-intro.adoc`
```asciidoc
= Intro

...
```

After some digging I found that the `:source-highlighter:` attribute was not picked up by Asciidoc-revealjs because the first heading was on the second level (`==` instead of `=`). By changing the heading to first level, the syntax highlighting suddenly worked.

I don't know enough of the Asciidoctor internal document format to decide if this is something that could be changed, or that it just is the way it is. That's why I'm looking for advice here. 

### Slide-breaks not working / Slides rendered _inside_ a slide

The above series of documents shows another issue. Every included document started with a first-level heading (`=`):

`01-intro.adoc`
```asciidoc
= Intro

...
```

This caused revealjs to generate a slide for the heading `Intro` and all subsequent headings in that file were rendered as slides (`<section>`) _within_ the `<section>` for the `Intro` heading. 

Again, the question is whether this is behavior that is inherent to Asciidocs internal document structure or not. If it is, then I would propose adding a little section in "Write your presentation" that would explain this situation and outline that the root document should only have first-level headings and any included documents should have deeper nested headings.

Dear maintainers, what say you? Are these "undocumented features" to be documented, or are they bugs?

**Comment by mojavelinux** [comment]
>  There seem to be assumptions about root-level headings (with just 1 =) that influence whether certain features are correctly turned on. The main question is: is this a bug or is it something that we should document as a caveat/troubleshooting thing?

This assumption isn't just specific to this converter. It is a fundamental part of the AsciiDoc language. The first level-0 section title (i.e., the doctitle) marks the beginning of the document header. Document-scoped attributes that impact the converter can **only** be set in the document header. See https://docs.asciidoctor.org/asciidoc/latest/document/header/

We've tried to be as clear as we can about this in the AsciiDoc docs. If you have a better way to phrase, please let us know.

**Comment by jhkuperus** [comment]
Thanks for the clear demonstration. I figured out that the structure was the problem. The slides were the result of some collaborative work and that's why the headings were not uniform. It took me a lot of time to see that that was the actual problem. Reading the pages you are referencing definitely clears that up.

To be perfectly honest, AsciiDoc is relatively new to me and we jumped right into generating slides. Since the highlighting didn't work, I was looking for the source of my problem in de docs on the revealjs converter. I'm wondering how to prevent the next person from spending too much time on this. 

Maybe the "Syntax Highlighting" section could have a paragraph "Troubleshooting":

> If syntax highlighting does not appear to work, make sure the document follows the general structure of an AsciiDoc
> document and that the `:source-highlighter:` attributes is defined in the Document Header (with URL to the header docs).

And perhaps include the example with a section title at the start instead of a document title.

Or maybe it is enough for the internet to index this issue? 😅

**Comment by mojavelinux** [comment]
I'm glad that information was helpful. It's very important for us to hear from users of all backgrounds so we understand how to write instructions that are universally understood.

> Maybe the "Syntax Highlighting" section could have a paragraph "Troubleshooting":

I think we could go up a level. I think the documentation for the revealjs converter could emphasize the importance of the document header and link to the relevant page in the AsciiDoc docs. I'm thinking something like a link from https://docs.asciidoctor.org/reveal.js-converter/latest/converter/features/#basic-presentation-with-speaker-notes to https://docs.asciidoctor.org/reveal.js-converter/latest/converter/syntax/title/ then to https://docs.asciidoctor.org/asciidoc/latest/document/header/. There should be a clear statement that the document header is what configures the presentation. I think that would help users get off to the right start.

> And perhaps include the example with a section title at the start instead of a document title.

I like that idea.

**Comment by jhkuperus** [comment]
Alright, I'll fork and work on a draft.
