### ISSUE TITLE
Help wanted: custom templates are missing methods

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-reveal.js#482]
When I just copy olist.slim.html to my custom templates folder it fails with

undefined method `data-attrs' for #<Asciidoctor::List (running on jruby)

other (no custom methods) templates are working fine.

Does anyone have an idea where this could be fixed? Is this an asciidoctor upstream problem?

**Comment by Mogztter** [comment]
This function is part of the helpers.rb file: https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/helpers.rb#L99

So you will need to copy it as well. Asciidoctor will automatically requires it (via the TemplateConverter: https://github.com/asciidoctor/asciidoctor/blob/a70a70239077d9d97a74e75db7da6a24c8065264/lib/asciidoctor/converter/template.rb#L244)

**Comment by Mogztter** [comment]
In the future, please ask questions in the community chat at https://chat.asciidoctor.org

**Comment by eiswind** [comment]
@Mogztter Thanks for helping me out. I'll try the chat next time. This ruby stuff is very challenging to me :)
