### ISSUE TITLE
document preamble (text after title before first section) is shown on every slide

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#49]
A bug present in both deck.js and reveal.js related to the fact that block_preamble is processed after the title slide and will slip the content through inside a `<div>` which will not be properly nested inside the title's `<section>` element.

Already discussed here: http://discuss.asciidoctor.org/Using-Preambel-with-deck-js-scrambles-output-td2154.html

I don't think the solution of having the preamble in its own slide to be the proper one with regards to what one would expect when writing slides. I tried and failed to implement the second solution mentioned in the discussion.

@mojavelinux I tried listing attributes and can't find any attribute to match that would say: "this is the first slide". A section number would do. Also, it is unclear to me how to grab content of another block from within another template. Help appreciated :)

**Comment by mojavelinux** [comment]
You can traverse the AST from any template. You can use `.parent` to get to the parent and `find_by` to locate descendant elements.

To get to the preamble from the document template, use:

```
doc.find_by context: :preamble
```

That gets you an array of results. If a preamble exists, it will be returned.

I think it makes the most sense to put preamble content on the title slide (or to just drop it). I agree it probably doesn't make sense to make a dedicated slide.
