### ISSUE TITLE
Remote presentation shows only source code of presentation notes

### ISSUE THREAD

**Issue by ericzolf** [asciidoctor/asciidoctor-reveal.js#490]
The [Ruby setup instructions](https://docs.asciidoctor.org/reveal.js-converter/latest/setup/ruby-setup/) explain how to refer to revealjs locally (downloading the Git repo) or remotely. When using the remote method, the "s" calls a pop-up window containing only the HTML code for the speaker notes, instead of the normal "console" (which appears in local mode).

I've created a small repeater script:
[asciidoc-revealjs.sh.txt](https://github.com/asciidoctor/asciidoctor-reveal.js/files/10368102/asciidoc-revealjs.sh.txt)
(1st parameter is the name of a directory where to create the presentation; the 2nd parameter if present and equal to "local" downloads the revealjs-Git repo, else revealjs is used remotely, which as said doesn't work properly).

Either something is wrong with the instructions, or something is broken (possibly between chair and keyboard).

I'm using chromium-freeworld under Fedora 37: chromium-freeworld-108.0.5359.124-1.fc37.x86_64. I also tried with firefox-108.0.1-3.fc37.x86_64, and the behavior is very similar.

Remote: ![image](https://user-images.githubusercontent.com/3105685/211190207-df4dfa69-e4b5-4a37-9150-1df9d2dde4a2.png)
vs. Local: 
![image](https://user-images.githubusercontent.com/3105685/211190343-713bace9-0d34-42ce-ac8a-c2bcd290765a.png)

**Comment by Mogztter** [comment]
The reason is that https://cdn.jsdelivr.net/npm/reveal.js@3.9.2/plugin/notes/notes.html is served as `text/plain` (not HTML). Apparently, for security reasons: https://github.com/jsdelivr/jsdelivr/issues/18027

I don't really know if there's a workaround.

**Comment by refaelsh** [comment]
I have the same problem too.
