### ISSUE TITLE
Multiple authors not taken into consideration in revealjs output.

### ISSUE THREAD

**Issue by barthel** [asciidoctor/asciidoctor-reveal.js#495]
This behavior was reported with #122 several years ago and was actually fixed.

Unfortunately, I had to find out that the treatment of multiple authors currently (again) does not work.

I followed this guide and tried the example: https://docs.asciidoctor.org/asciidoc/latest/document/multiple-authors/

The content of `slides_author.adoc` looks like:
```
= The Intrepid Chronicles
Kismet R. Lee <kismet@asciidoctor.org>; B. Steppenwolf; Pax Draeke <pax@asciidoctor.org>
```

Generating the HTML with the following command and copy the `reveal.js` resources into `/documents/slides`:
```bash
> docker run --rm -v ${PWD}:/documents asciidoctor/docker-asciidoctor:1.41.0 asciidoctor-revealjs -D /documents/slides/ /documents/src/slides/slides_author.adoc
```

Only the first author is displayed and also without email:
![Screenshot 2023-03-30 at 07-14-19 The Intrepid Chronicles](https://user-images.githubusercontent.com/1170328/228737106-a1854d99-3103-470b-8090-5e8fabf3f5b3.png)

revea.js version: 3.9.2
```bash
> docker run --rm -v ${PWD}:/documents asciidoctor/docker-asciidoctor:1.41.0 asciidoctor-revealjs -V
Asciidoctor reveal.js 4.1.0 using Asciidoctor 2.0.18 [https://asciidoctor.org]
Runtime Environment (ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by refaelsh** [comment]
I am experiencing the same issue.

**Comment by ggrossetie** [comment]
It was fixed in https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v5.0.0-rc.1
