### ISSUE TITLE
Source code block highlighting for Haskell

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor-reveal.js#504]
Here is an example to reproduce the problem:
```asciidoctor
snip
:source-highlighter: highlightjs
snip

[source, haskell, linenums]
----
reverselist [a] -> [a]
reverseList list = ...

doubleList [a] -> [a]
doubleList list = ...

reversedAndDoubled [a] -> [a]
reversedAndDoubled list = reverselist (doublelist list)

-- Or using function composition:
reversedAndDoubled [a] -> [a]
reversedAndDoubled = reverselist . doublelist
----
```

I don't see that the code block has highlighting. It works for C++ for example.

**Comment by ggrossetie** [comment]
Did you set the `highlightjs-languages` attribute?

```
:highlightjs-languages: haskell
```

https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/highlightjs/#load-support-for-additional-languages

In the future, please ask questions in the community chat: https://chat.asciidoctor.org

**Comment by refaelsh** [comment]
I understand. Thank you very much. 

> In the future, please ask questions in the community chat: https://chat.asciidoctor.org/

Duly noted.
