### ISSUE TITLE
The :email: thingy is disregarded in the title slide

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/asciidoctor-reveal.js#505]
Here is an adoc to reproduce it:
```
= Oh, this pesky state..
:author: Refael Sheinker
:email: refaelsh@pm.me

== Some slide
Lorem ipsum
```
Here is how it looks:
![Untitled](https://github.com/asciidoctor/asciidoctor-reveal.js/assets/2750775/47c28593-fb1a-4fea-8bac-dd828385336d)
No email appears. I think its a bug.

**Comment by ggrossetie** [comment]
It was fixed in https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v5.0.0-rc.1

**Comment by refaelsh** [comment]
Oh, cool. Thank you :-)
