### ISSUE TITLE
Setup repository to work with Bower

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-reveal.js#57]
Setup the repository so that Bower can be used to fetch the templates. This will allow Bower to be used to manage both Reveal.js and the templates so that no manual cloning steps are required.

There are two steps required here:

1. Create a bower.json file that identifies which files to fetch / ignore
1. Register the repository in the Bower index

(2) is technically optional as the repository can be referenced using the git URL, but it's nicer if we can get into the index officially.

**Comment by obilodeau** [comment]
Enlighten me, what is the difference between Bower and npm?

**Comment by mojavelinux** [comment]
Bower has become less relevant now that npm has grown in popularity. Technically, the difference is that Bower does not require packaging. It's really just a way to depend on a git repository to get web assets, so a bit less formal.

In general I'd say this becomes wholly unnecessary if we just have a formal converter entry point and release it as a gem.

**Comment by obilodeau** [comment]
Thanks for the answer! Closing this in favor of #93.
