### ISSUE TITLE
Make project license explicit

### ISSUE THREAD

**Issue by nicorikken** [asciidoctor/asciidoctor-reveal.js#65]
Now the project license is not clearly stated, which complicates reuse, modifications, and even distribution of asciidoctor-reveal.js based presentations.

**Comment by mojavelinux** [comment]
The license file got lost when the code was moved from asciidoctor-backends. It should be the MIT license.

**Comment by mojavelinux** [comment]
Actually, it looks like a license is missing from that repository too. I'll update it there.

**Comment by mojavelinux** [comment]
Here's the file: https://github.com/asciidoctor/asciidoctor-backends/blob/master/LICENSE.adoc

Feel free to add additional authors, but please end it with "and the Asciidoctor Project"

**Comment by nicorikken** [comment]
Thanks for the great speed. I've answered it by doing a morning commit.

**Comment by mojavelinux** [comment]
:+1:

**Comment by obilodeau** [comment]
Thanks @nicorikken!
