### ISSUE TITLE
Background image doesn't work on the title slide

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-reveal.js#7]
The background image, controlled by the `data-background` block attribute and related attributes, doesn't work on the title slide.

In general, the `<section>` element generated from the document title of the AsciiDoc document should have all the same capabilities as the `<section>` element generated from a section title.

**Comment by mojavelinux** [comment]
I propose the following document-level attributes to control this behavior:

* title-slide-background-image
* title-slide-background-size
* title-slide-background-color

...and so forth. I'd be happy if just those are supported to start.

The background image value should be resolved relative to the imagesdir.

We could also entertain the idea of using the image macro syntax in the value of the title-slide-background-image to consolidate information (e.g., `image:bg.png[size=cover]`)

**Comment by danhyun** [comment]
I'd be happy to have those too :) Maybe we can also allow for vertical and horizontal positioning

**Comment by danhyun** [comment]
So we have background image trumping color and resolving image to imagesdir. Next is to tackle size and positioning. I've also added a plain `slide-background-image` to provide a default background image. There should probably be a corresponding color option.

**Comment by mojavelinux** [comment]
>  I've also added a plain slide-background-image to provide a default background image. 

Oooh, that's interesting!

I agree, `slide-background-color` would be nice.

We should probably create a utility method for handling the background options because the templates are getting a bit busy doing it long-hand. Slim now provides a nice mechanism for this as you can see in the templates from asciidoctor-backends. https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/helpers.rb You can also use the `include` directive as show here: https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/html5/document.html.slim#L23

**Comment by mojavelinux** [comment]
In the pull request I haven't yet sent, I added support for all the data-background stuff, including positioning. Here's the relevant bits from my local file:

```
      .slides
        - unless notitle || !has_header?
          - bg_image = (attr? 'title-slide-background-image') ? (image_uri(attr 'title-slide-background-image')) : nil
          section(class = role
            data-transition=(attr 'title-slide-transition')
            data-transition-speed=(attr 'title-slide-transition-speed')
            data-background=(attr 'title-slide-background')
            data-background-image=bg_image
            data-background-color=(attr 'title-slide-background-color')
            data-background-size=(attr 'title-slide-background-size')
            data-background-position=(attr 'title-slide-background-position')
            data-background-repeat=(attr 'title-slide-background-repeat')
            data-background-transition=(attr 'title-slide-background-transition'))
            h1=@header.title
```

I'll try to get around to sending these pull requests because I have a few of them just sitting here.

**Comment by danhyun** [comment]
See this is why you gotta look at the code. The docs for reveal.js mention nothing about `data-background-image`

Do you think we should support iframe?
https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L664-L674
```
var data = {
    background: slide.getAttribute( 'data-background' ),
    backgroundSize: slide.getAttribute( 'data-background-size' ),
    backgroundImage: slide.getAttribute( 'data-background-image' ),
    backgroundVideo: slide.getAttribute( 'data-background-video' ),
    backgroundIframe: slide.getAttribute( 'data-background-iframe' ),
    backgroundColor: slide.getAttribute( 'data-background-color' ),
    backgroundRepeat: slide.getAttribute( 'data-background-repeat' ),
    backgroundPosition: slide.getAttribute( 'data-background-position' ),
    backgroundTransition: slide.getAttribute( 'data-background-transition' )
};
```

At any rate I'd like to provide a set of document level attributes that mirror title slide attributes to be applied to all slides, letting each slide override of course.

I think it'd be good to get your PR in so we don't duplicate efforts, it'd be good to get this plus some other features in before gr8conf :D

**Comment by mojavelinux** [comment]
> Do you think we should support iframe?

Sure, why not.

> I'd like to provide a set of document level attributes that mirror title slide attributes to be applied to all slides

Very interesting indeed.

> I think it'd be good to get your PR in so we don't duplicate efforts

I'll send it over. Stay tuned.

Btw, once I send the pull request, you'll see why we need to start leveraging helpers.rb to keep this stuff DRY and keep the templates clean.

**Comment by mojavelinux** [comment]
I also added support for video. However, we should probably add a follow-up issue to allow the video to be a YouTube or Vimeo video as shorthand (e.g, `youtube:123xyz`)

**Comment by andreabedini** [comment]
news? :)

**Comment by mojavelinux** [comment]
See discussion in open PR https://github.com/asciidoctor/asciidoctor-reveal.js/pull/34
