### ISSUE TITLE
fontawesome does not show under IE11

### ISSUE THREAD

**Issue by bodtx** [asciidoctor/asciidoctor-reveal.js#72]
When I use this in my slide:
`icon:cogs[]`
it works when I render in HTML5
it does not show when I render in revealJS

**Comment by mojavelinux** [comment]
Is this specific to IE11, or do icons not show at all?

Have you enabled the icons attribute in the document header?

```
:icons: font
```

**Comment by bodtx** [comment]
Yes I have, but problem solved this morning it is working, probably a cache problem, sorry
