### ISSUE TITLE
Possibility to define class as atttributes to images

### ISSUE THREAD

**Issue by ochaloup** [asciidoctor/asciidoctor-reveal.js#74]
Hi,

as I don't know where to put my questions or doubt on for asciidoctor-reveal.js project I've decided to create an issue. If this is wrong way could you please close this and refer me to the correct place?

Nevertheless I would like to have possibility to define a `class` for images which are part of the slide deck. What do you think?

I've tried to do it in this way
https://github.com/ochaloup/asciidoctor-reveal.js/commit/ebed6b938065b5e0938253be936d916b945984a2

Thanks
Ondra

**Comment by mojavelinux** [comment]
The role attribute is already reserved for this purpose. The role is added to the surrounding imageblock div. You can use nested CSS rules to style the image.

```
image::picture.jpg[role=border]
```

```
.imageblock.border img {
  border: 3px solid gray;
}
```

**Comment by ochaloup** [comment]
ok, that's it. Thanks a lot. Haven't dig down to this. Issue solved.
