### ISSUE TITLE
Turn asciidoctor-reveal.js into a proper back-end

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#78]
Need to add code like this to the repository: https://github.com/asciidoctor/asciidoctor-bespoke/blob/master/lib/asciidoctor-bespoke/converter.rb

As discussed in #68

**Comment by mojavelinux** [comment]
See sample code in the following comment:

https://github.com/asciidoctor/asciidoctor-reveal.js/issues/68#issuecomment-243336091

**Comment by obilodeau** [comment]
Thanks for that. Looking forward to implement that change. I looked at the bespoke back-end a bit yesterday and I'm really impressed!

The template presentation with instructions is very neat also.

**Comment by obilodeau** [comment]
Feature implemented in #93. Closing.
