### ISSUE TITLE
Applying reveal.js' stretch class doesn't give intended result for images

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#82]
Revealjs has a feature called stretch to give the focus to a specific HTML element: https://github.com/hakimel/reveal.js#stretching-elements

It works by using javascript to assign a style with height and width to the specific element. The javascript is not executed when changing slides since I tried setting the attribute directly in chrome's developer console and it did not work.

One problem is the following limitation of the stretch feature:
> Only direct descendants of a slide section can be stretched

Currently, this back-end wraps in HTML tags heavily. Images are wrapped in `imageblock` then a `div.content` and finally the image tag (if there's no link). The nesting means `stretch` won't work.

We need to think about what we can do to benefit from this `stretch` class which applies directly the exact amount of pixels we can expand to without clobbering the rest of the content.

**Comment by mojavelinux** [comment]
> Currently, this back-end wraps in HTML tags heavily. Images are wrapped in imageblock then a div.content and finally the image tag (if there's no link). The nesting means stretch won't work.

Don't hesitate to change the HTML structure. As I mentioned in another comment, I'd like to see modern HTML used for images like what's in the Bespoke converter (i.e., figure/figcaption). (See https://github.com/asciidoctor/asciidoctor-bespoke/blob/master/templates/slim/image.html.slim). In general, we should be gravitating towards modern HTML which also works best with Reveal.js. We have to strike a balance.

**Comment by obilodeau** [comment]
Yes, let's aim to do modern HTML wherever we can.

That said, there is a conflict here. First is that using `figure` means wrapping `img` in another tag and will make `.stretch` not work (it works only to direct descendants of slide content). Second, as I said in #81, re-doing the equivalent of what .stretch does in pure CSS really challenges my CSS skills.

So I would close this since it's fixed in master. Then the day someone figures it out in pure CSS  (pun unintended) we'll go down the `figure` road.

Thoughts?

**Comment by obilodeau** [comment]
No comments, closing. Open a new bug if necessary.

**Comment by mojavelinux** [comment]
> So I would close this since it's fixed in master. Then the day someone figures it out in pure CSS (pun unintended) we'll go down the figure road.

This is consistent with our philosophy that the converter should create HTML that fits best with the engine. Reveal.js doesn't recognize proper semantic structure in this case, so we shouldn't try to force it. I will use the proper semantic structure in the Bespoke.js converter since Bespoke.js doesn't not impose these types of limitations. And I think that's a reasonable strategy.
