### ISSUE TITLE
role attribute not applied to <section> (slides)

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#86]
Like this:

```
[.epic]
== Epic slide
```

Doesn't add an `epic` class to the `<section>` HTML tag.

This makes CSS customization harder than it should be.

**Comment by obilodeau** [comment]
Implemented it in an existing PR due to invasive changes that would conflict otherwise and PR is soon to be merged.

**Comment by mojavelinux** [comment]
:+1:
