### ISSUE TITLE
Error generated if the asciidoctor source-highlighter: 'highlight.js' is not defined

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor-reveal.js#88]
This error is reported when we process the file using asciidoctor.js if the asciidoctor source-highlighter: 'highlight.js' attribute is not defined

![screenshot 2016-09-05 12 31 43](https://cloud.githubusercontent.com/assets/463790/18245966/9936f47c-7368-11e6-85e6-d455fb6186d9.png)

Maybe this code should be improved to define a default value 

https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/jade/document.jade#L90

**Comment by Mogztter** [comment]
I'm experiencing another issue. In my case `dependencies` attribute is:

```javascript
dependencies: [
            {
              src: 'reveal.js/lib/js/classList.js', condition: function () {
              return !document.body.classList;
            }
            },
            {},
            {
              src: 'reveal.js/plugin/zoom-js/zoom.js', async: true, condition: function () {
              return !!document.body.classList;
            }
            },
            {
              src: 'reveal.js/plugin/notes/notes.js', async: true, condition: function () {
              return !!document.body.classList;
            }
            }
          ]
```

The problem is that reveal.js does not work with an empty object:

```
reveal.js Uncaught TypeError: Cannot read property 'match' of undefined
```
https://github.com/hakimel/reveal.js/blob/539e774d31f91676bcc3f75e28168921cd27d819/js/reveal.js#L370

`s.src` is undefined

**Comment by cmoulliard** [comment]
Maybe we should add nil like the slim template in this case --> https://github.com/asciidoctor/asciidoctor-reveal.js/blob/master/templates/slim/document.html.slim#L173

**Comment by cmoulliard** [comment]
This workaround which is not great works for jade --> Replace `{},` with `{ src: ''},`

**Comment by mojavelinux** [comment]
The correct value is empty string. In the Slim/Ruby template, nil is equivalent to empty string. We definitely don't want to emit an empty JSON object. That's just asking for trouble.

**Comment by cmoulliard** [comment]
You are right @mojavelinux, I have changed the line as such

```
#{(node.$attr('source-highlighter') == 'highlight.js') ? "{ src: '#{revealjsdir}/plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }," : ""}
```

I will submit a PR to include this modification

**Comment by cmoulliard** [comment]
Solution : https://github.com/asciidoctor/asciidoctor-reveal.js/pull/101

**Comment by Mogztter** [comment]
@cmoulliard I've also fixed this issue in https://github.com/asciidoctor/asciidoctor-reveal.js/pull/95 but it's better to have a dedicated pull request :wink:
