### ISSUE TITLE
Add missing jade template - thematic_break.jade

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor-reveal.js#89]
Aciidoctor processor supports to add a break (Horizontal rule, ...) using this node : http://www.rubydoc.info/github/asciidoctor/asciidoctor/Asciidoctor%2FConverter%2FHtml5Converter%3Athematic_break which is implemented within the slim template but not jade

**Comment by obilodeau** [comment]
This is a duplicate of #63. I will close it. Once slim/jade are on par with each other then we can open individual issues on differences but right now this will just create too many issues.
