### ISSUE TITLE
Compatibility issue with reveal.js 3.0.0

### ISSUE THREAD

**Issue by antoinesd** [asciidoctor/asciidoctor-reveal.js#9]
With reveal.js the produced HTML is a static html page. I lost a couple of hours to discover that. At least it should be stated in the readme file until compatibility is set.

**Comment by mojavelinux** [comment]
I agree. Would you like to update the README?

**Comment by antoinesd** [comment]
yes of course.

**Comment by antoinesd** [comment]
sent PR #10

**Comment by mojavelinux** [comment]
Merci!

**Comment by danhyun** [comment]
Now I know to use 2.6.2 :)

**Comment by mojavelinux** [comment]
I'd be glad to see this backend upgrade to 3.0.0, if someone is willing to submit a fix. Let's more it forward!

**Comment by obilodeau** [comment]
Something has been submitted: #12

**Comment by mojavelinux** [comment]
Resolved by #12.
