### ISSUE TITLE
Implement asciidoctor-doctest testing

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-reveal.js#92]
We should implement [asciidoctor-doctest](https://github.com/asciidoctor/asciidoctor-doctest/). See [asciidoctor-backends](https://github.com/asciidoctor/asciidoctor-backends/) for an example implementation.

Idea / suggestion came from @jirutka during this discussion #63.
- [x] migrate from Makefile and manual tests to asciidoctor-doctest
- [x] create travis-ci integration and run doctest as part of build

**Comment by obilodeau** [comment]
As mentioned by @mojavelinux, we should use rake for tests

**Comment by jirutka** [comment]
Rake for tests? o.O Rake is like Make…

**Comment by obilodeau** [comment]
To run the tests, instead of make

**Comment by obilodeau** [comment]
See https://github.com/asciidoctor/asciidoctor-reveal.js/pull/110#issuecomment-251581555

**Comment by obilodeau** [comment]
Faced a problem trying to get the tests to run, filed a bug to upstream project in order to get help: asciidoctor/asciidoctor-doctest#11

For anyone interested, work-in-progress branch is here: [obilodeau/asciidoctor-reveal.js](https://github.com/obilodeau/asciidoctor-reveal.js/tree/doctest)

It is, again, due to my misunderstanding of the whole gem, bundler and ruby packaging ecosystem...

**Comment by obilodeau** [comment]
Making some progress. Until further notice, refer to the pull request #116 to follow what is happening.

**Comment by obilodeau** [comment]
With #116 in master, this has been implemented.
